/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Servicios;

import ConexionLogin.Conexion;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.text.Normalizer;
public class PreciosServiciosCajero extends javax.swing.JFrame {

    /**
     * Creates new form PreciosServiciosCajero
     */
    public PreciosServiciosCajero() {
        initComponents();
        cargarTabla();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            @Override
            public void windowGainedFocus(java.awt.event.WindowEvent e) {
            }

            @Override
            public void windowLostFocus(java.awt.event.WindowEvent e) {

                dispose();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListaPersonal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ListaPersonal1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BuscarServicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServicios = new javax.swing.JTable();
        FondoGris1 = new javax.swing.JLabel();

        ListaPersonal.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        ListaPersonal.setText("Seleccionar Médico");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaPersonal1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        ListaPersonal1.setText("Servicios");
        jPanel1.add(ListaPersonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 340, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 30, 30));

        BuscarServicio.setBackground(new java.awt.Color(233, 236, 239));
        BuscarServicio.setText("Buscar");
        BuscarServicio.setToolTipText("");
        BuscarServicio.setBorder(null);
        BuscarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarServicioActionPerformed(evt);
            }
        });
        jPanel1.add(BuscarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 140, 30));
        String placeholder = "Buscar Servicio";

        BuscarServicio.setText(placeholder);
        BuscarServicio.setForeground(Color.GRAY);

        BuscarServicio.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (BuscarServicio.getText().equals(placeholder)) {
                    BuscarServicio.setText("");
                    BuscarServicio.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (BuscarServicio.getText().isEmpty()) {
                    BuscarServicio.setText(placeholder);
                    BuscarServicio.setForeground(Color.GRAY);
                }
            }
        });

        BuscarServicio.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable();
            }

            private void filterTable() {
                String query = quitarTildes(BuscarServicio.getText().toLowerCase().trim());

                if (query.equals(quitarTildes(placeholder.toLowerCase()))) {
                    tblServicios.setRowSorter(null);
                    return;
                }

                TableRowSorter<TableModel> sorter = (TableRowSorter<TableModel>) tblServicios.getRowSorter();
                if (sorter == null) {
                    sorter = new TableRowSorter<>(tblServicios.getModel());
                    tblServicios.setRowSorter(sorter);
                }

                if (query.isEmpty()) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(new RowFilter<TableModel, Integer>() {
                        @Override
                        public boolean include(Entry<? extends TableModel, ? extends Integer> entry) {

                            String servicio = quitarTildes(entry.getStringValue(1).toLowerCase());
                            return servicio.contains(query);
                        }
                    });
                }
            }

        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 190, 30));

        tblServicios.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Precio", "Precio de Emergencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblServicios.setToolTipText("");
        tblServicios.getTableHeader().setReorderingAllowed(false);
        tblServicios.getTableHeader().setResizingAllowed(false);
        tblServicios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblServicios.setFocusable(false);
        jScrollPane2.setViewportView(tblServicios);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 990, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1010, 500));

        FondoGris1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_3.png"))); // NOI18N
        getContentPane().add(FondoGris1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarTabla() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        modelo.setColumnIdentifiers(new Object[]{
            "ID", "Nombre del Servicio", "Descripción", "Precio Normal", "Precio Emergencia"
        });

        try {
            Connection con = Conexion.obtenerConexion();
            PreparedStatement ps = con.prepareStatement(
                    "SELECT id_servicio, nombre_servicio, descripcion, precio_normal, precio_emergencia FROM servicios WHERE estado = 1"
            );
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("id_servicio"),
                    rs.getString("nombre_servicio"),
                    rs.getString("descripcion"),
                    rs.getDouble("precio_normal"),
                    rs.getDouble("precio_emergencia")
                });
            }

            tblServicios.setModel(modelo);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar los servicios: " + ex.getMessage());
            ex.printStackTrace();
        }
    }
    private String quitarTildes(String texto) {
        if (texto == null) {
            return "";
        }
        texto = Normalizer.normalize(texto, Normalizer.Form.NFD);
        return texto.replaceAll("\\p{InCombiningDiacriticalMarks}+", "");
    }
    private void BuscarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreciosServiciosCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuscarServicio;
    private javax.swing.JLabel FondoGris1;
    private javax.swing.JLabel ListaPersonal;
    private javax.swing.JLabel ListaPersonal1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblServicios;
    // End of variables declaration//GEN-END:variables
}
