/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Servicios;

import ConexionLogin.Conexion;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.text.Normalizer;

/**
 *
 * @author Rafael
 */
public class SeleccionarDoc extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarDoc
     */
    private JTextField campoDestino;
    public SeleccionarDoc(JTextField campoDestino) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.campoDestino = campoDestino;
        cargarTabla();

        
    }

    private SeleccionarDoc() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMedicos = new javax.swing.JTable();
        ListaPersonal = new javax.swing.JLabel();
        DatosMedico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        BuscarDoctores = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FondoGris1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "CI", "Categoria Profesional", "Especialidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMedicosMouseClicked(evt);
            }
        });
        TablaMedicos.getTableHeader().setReorderingAllowed(false);
        TablaMedicos.getTableHeader().setResizingAllowed(false);
        TablaMedicos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaMedicos.setFocusable(false);
        jScrollPane1.setViewportView(TablaMedicos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 1090, 430));

        ListaPersonal.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        ListaPersonal.setText("Seleccionar Médico");
        getContentPane().add(ListaPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 340, -1));

        DatosMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatosMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(DatosMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 330, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Médico:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        BuscarDoctores.setBackground(new java.awt.Color(233, 236, 239));
        BuscarDoctores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BuscarDoctores.setText("Buscar");
        BuscarDoctores.setToolTipText("");
        BuscarDoctores.setBorder(null);
        BuscarDoctores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarDoctoresActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarDoctores, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 140, 20));
        String placeholder = "Buscar Doctor";

        BuscarDoctores.setText(placeholder);
        BuscarDoctores.setForeground(Color.GRAY);

        BuscarDoctores.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (BuscarDoctores.getText().equals(placeholder)) {
                    BuscarDoctores.setText("");
                    BuscarDoctores.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (BuscarDoctores.getText().isEmpty()) {
                    BuscarDoctores.setText(placeholder);
                    BuscarDoctores.setForeground(Color.GRAY);
                }
            }
        });

        BuscarDoctores.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable();
            }

            private void filterTable() {
                String query = quitarTildes(BuscarDoctores.getText().toLowerCase().trim());

                if (query.equals(quitarTildes(placeholder.toLowerCase()))) {
                    TablaMedicos.setRowSorter(null);
                    return;
                }

                TableRowSorter<TableModel> sorter = (TableRowSorter<TableModel>) TablaMedicos.getRowSorter();
                if (sorter == null) {
                    sorter = new TableRowSorter<>(TablaMedicos.getModel());
                    TablaMedicos.setRowSorter(sorter);
                }

                if (query.isEmpty()) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(new RowFilter<TableModel, Integer>() {
                        @Override
                        public boolean include(Entry<? extends TableModel, ? extends Integer> entry) {
                            // Columnas 1 (nombre) y 2 (apellido)
                            String nombre = quitarTildes(entry.getStringValue(1).toLowerCase());
                            String apellido = quitarTildes(entry.getStringValue(2).toLowerCase());
                            return nombre.contains(query) || apellido.contains(query);
                        }
                    });
                }
            }

        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 190, 40));

        FondoGris1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_3.png"))); // NOI18N
        getContentPane().add(FondoGris1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("CI");
        modelo.addColumn("Categoría Profesional");
        modelo.addColumn("Especialidad");

        String docBuscado = DatosMedico.getText().trim();

        try {
            Connection con = Conexion.obtenerConexion();
            String sql;

            if (docBuscado.isEmpty()) {
                // Mostrar todos los médicos activos
                sql = "SELECT id_medico, CI, nombre, apellido, categoria_profesional, categoria_profesional_otro, especialidad FROM medicos WHERE estado = 1";
            } else {
                // Buscar por CI, Nombre o Apellido que contengan el texto buscado
                sql = "SELECT id_medico, CI, nombre, apellido, categoria_profesional, categoria_profesional_otro, especialidad FROM medicos WHERE estado = 1 AND (CI LIKE ? OR nombre LIKE ? OR apellido LIKE ?)";
            }

            PreparedStatement pst = con.prepareStatement(sql);

            if (!docBuscado.isEmpty()) {
                String filtro = "%" + docBuscado + "%";
                pst.setString(1, filtro);
                pst.setString(2, filtro);
                pst.setString(3, filtro);
            }

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String categoria = rs.getString("categoria_profesional");
                String otro = rs.getString("categoria_profesional_otro");

                String categoriaMostrar;
                if ("Otro".equalsIgnoreCase(categoria) && otro != null && !otro.trim().isEmpty()) {
                    categoriaMostrar = otro;
                } else {
                    categoriaMostrar = categoria;
                }

                Object[] fila = new Object[6];
                fila[0] = rs.getInt("id_medico");
                fila[1] = rs.getString("nombre");
                fila[2] = rs.getString("apellido");
                fila[3] = rs.getString("CI");
                fila[4] = categoriaMostrar;
                fila[5] = rs.getString("especialidad");

                modelo.addRow(fila);
            }

            TablaMedicos.setModel(modelo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los médicos: " + e.getMessage());
        }
    }

    private String quitarTildes(String texto) {
        if (texto == null) {
            return "";
        }
        texto = Normalizer.normalize(texto, Normalizer.Form.NFD);
        return texto.replaceAll("\\p{InCombiningDiacriticalMarks}+", "");
    }
    
    private void TablaMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMedicosMouseClicked
        int filaSeleccionada = TablaMedicos.getSelectedRow();
        if (filaSeleccionada != -1) {
            String nombre = TablaMedicos.getValueAt(filaSeleccionada, 1).toString();
            String apellido = TablaMedicos.getValueAt(filaSeleccionada, 2).toString();
            String nombreCompleto = nombre + " " + apellido;
            DatosMedico.setText(nombreCompleto);
        }
    }//GEN-LAST:event_TablaMedicosMouseClicked

    private void DatosMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatosMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatosMedicoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int filaSeleccionada = TablaMedicos.getSelectedRow();
        if (filaSeleccionada != -1) {
            String nombre = TablaMedicos.getValueAt(filaSeleccionada, 1).toString();
            String apellido = TablaMedicos.getValueAt(filaSeleccionada, 2).toString();
            String nombreCompleto = nombre + " " + apellido;
            campoDestino.setText(nombreCompleto);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un doctor para guardar.");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void BuscarDoctoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarDoctoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarDoctoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e){
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarDoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuscarDoctores;
    private javax.swing.JTextField DatosMedico;
    private javax.swing.JLabel FondoGris1;
    private javax.swing.JLabel ListaPersonal;
    private javax.swing.JTable TablaMedicos;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
