/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Servicios;

import ConexionLogin.Conexion;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Rafael
 */
public class ServiciosPrecios extends javax.swing.JFrame {

    /**
     * Creates new form ServiciosPrecios
     */
    public ServiciosPrecios() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Superior = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Categoria = new javax.swing.JLabel();
        btnRedes = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        btnTelecomunicaciones = new javax.swing.JButton();
        btnElectronica = new javax.swing.JButton();
        MostrarTodo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServicios = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        NombreServicio = new javax.swing.JTextField();
        txtID1 = new javax.swing.JTextField();
        NombreService = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descripcion = new javax.swing.JTextArea();
        Desc = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnModificar1 = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        CostoServicio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(247, 248, 252));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Superior.setBackground(new java.awt.Color(80, 35, 100));
        Superior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel1.setText("Servicios");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Categoria.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        Categoria.setText("Categoria");
        jPanel3.add(Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        btnRedes.setBackground(new java.awt.Color(29, 41, 57));
        btnRedes.setForeground(new java.awt.Color(255, 255, 255));
        btnRedes.setText("Redes");
        btnRedes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedesActionPerformed(evt);
            }
        });
        jPanel3.add(btnRedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, -1));

        Limpiar.setBackground(new java.awt.Color(255, 0, 0));
        Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        Limpiar.setText("Limpiar");
        Limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        btnTelecomunicaciones.setBackground(new java.awt.Color(29, 41, 57));
        btnTelecomunicaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnTelecomunicaciones.setText("Telecomunicaciones");
        btnTelecomunicaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelecomunicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelecomunicacionesActionPerformed(evt);
            }
        });
        jPanel3.add(btnTelecomunicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, -1));

        btnElectronica.setBackground(new java.awt.Color(29, 41, 57));
        btnElectronica.setForeground(new java.awt.Color(255, 255, 255));
        btnElectronica.setText("Electronica");
        btnElectronica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnElectronica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElectronicaActionPerformed(evt);
            }
        });
        jPanel3.add(btnElectronica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        MostrarTodo.setBackground(new java.awt.Color(29, 41, 57));
        MostrarTodo.setForeground(new java.awt.Color(255, 255, 255));
        MostrarTodo.setText("Mostrar Todo");
        MostrarTodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTodoActionPerformed(evt);
            }
        });
        jPanel3.add(MostrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 570, 10, 200));

        tblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Precio", "Precio de Emergencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblServicios.setToolTipText("");
        int[]anchos = {50, 200, 200, 130, 100};
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < anchos.length; i++) {
            tblServicios.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            tblServicios.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        tblServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServiciosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblServicios);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1190, 860));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(233, 236, 239));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setText("Buscar ID");
        jTextField1.setToolTipText("");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 15, 90, 20));
        String placeholder = "Buscar ID";
        jTextField1.setText(placeholder);
        jTextField1.setForeground(Color.GRAY);
        jTextField1.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (jTextField1.getText().equals(placeholder)) {
                    jTextField1.setText("");
                    jTextField1.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (jTextField1.getText().isEmpty()) {
                    jTextField1.setText(placeholder);
                    jTextField1.setForeground(Color.GRAY);
                }
            }
        });
        jTextField1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable();
            }
            private void filterTable() {
                String query = jTextField1.getText().toLowerCase();
                if (query.equals(placeholder.toLowerCase())) {
                    tblServicios.setRowSorter(null);
                    return;
                }
                TableRowSorter<TableModel> sorter = new TableRowSorter<>(tblServicios.getModel());
                tblServicios.setRowSorter(sorter);
                if (query.trim().isEmpty()) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(RowFilter.regexFilter(query, 0));
                }
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_1.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 190, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1190, 710));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 194, 194)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(NombreServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 420, -1));

        txtID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID1ActionPerformed(evt);
            }
        });
        jPanel6.add(txtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, -48, 20, 40));

        NombreService.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NombreService.setText("Nombre del Servicio:");
        jPanel6.add(NombreService, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        Descripcion.setColumns(20);
        Descripcion.setRows(5);
        jScrollPane1.setViewportView(Descripcion);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 420, 130));

        Desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Desc.setText("Descripcion:");
        jPanel6.add(Desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel15.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel15.setText("Datos");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setBackground(new java.awt.Color(29, 41, 57));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, -1));

        btnModificar1.setBackground(new java.awt.Color(29, 41, 57));
        btnModificar1.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar1.setText("Modificar");
        btnModificar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 110, -1));

        btnLimpiar.setBackground(new java.awt.Color(29, 41, 57));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 110, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 110, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Costo:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        CostoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoServicioActionPerformed(evt);
            }
        });
        jPanel1.add(CostoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 420, -1));

        jLabel10.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel10.setText("Tarifa de Servicio");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, -1));

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 650, 140));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, 650, 370));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1880, 980));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void cargarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{
            "ID", "Nombre del Servicio", "Descripción", "Precio Normal", "Precio Emergencia"
        });

        try {
            Connection con = Conexion.obtenerConexion();
            PreparedStatement ps = con.prepareStatement(
                    "SELECT id_servicio, nombre_servicio, descripcion, precio_normal, precio_emergencia FROM servicios WHERE estado = 1"
            );
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("id_servicio"),
                    rs.getString("nombre_servicio"),
                    rs.getString("descripcion"),
                    rs.getDouble("precio_normal"),
                    rs.getDouble("precio_emergencia")
                });
            }

            tblServicios.setModel(modelo);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar los servicios: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    private void btnRedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedesActionPerformed

    }//GEN-LAST:event_btnRedesActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed

    }//GEN-LAST:event_LimpiarActionPerformed

    private void btnTelecomunicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelecomunicacionesActionPerformed

    }//GEN-LAST:event_btnTelecomunicacionesActionPerformed

    private void btnElectronicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElectronicaActionPerformed

    }//GEN-LAST:event_btnElectronicaActionPerformed

    private void MostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTodoActionPerformed

    }//GEN-LAST:event_MostrarTodoActionPerformed

    private void tblServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiciosMouseClicked

    }//GEN-LAST:event_tblServiciosMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombreTxt = NombreServicio.getText().trim();
        String descripcionTxt = Descripcion.getText().trim();
        String precioNormalTxt = CostoServicio.getText().trim();

        if (nombreTxt.isEmpty() || precioNormalTxt.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, rellene todos los campos obligatorios.");
            return;
        }

        double precioNormal;
        try {
            precioNormal = Double.parseDouble(precioNormalTxt);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El precio debe ser un número válido.");
            return;
        }

        double precioEmergencia = precioNormal * 1.3;

        try {
            Connection con = Conexion.obtenerConexion();

            PreparedStatement ps = con.prepareStatement(
                    "INSERT INTO servicios (nombre_servicio, descripcion, precio_normal, precio_emergencia) VALUES (?, ?, ?, ?)"
            );
            ps.setString(1, nombreTxt);
            if (descripcionTxt.isEmpty()) {
                ps.setNull(2, java.sql.Types.VARCHAR);
            } else {
                ps.setString(2, descripcionTxt);
            }
            ps.setDouble(3, precioNormal);
            ps.setDouble(4, precioEmergencia);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Servicio guardado correctamente.");

            limpiar();
            cargarTabla();
        } catch (SQLException ex) {
            if (ex.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "El nombre del servicio ya existe. Por favor, elija otro.");
            } else {
                JOptionPane.showMessageDialog(null, "Error en la base de datos: " + ex.getMessage());
            }
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
        int filaSeleccionada = tblServicios.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un servicio para modificar.");
            return;
        }

        int idServicio = (int) tblServicios.getValueAt(filaSeleccionada, 0);
        String nombreTxt = NombreServicio.getText().trim();
        String descripcionTxt = Descripcion.getText().trim();
        String precioNormalTxt = CostoServicio.getText().trim();

        if (nombreTxt.isEmpty() || precioNormalTxt.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, rellene todos los campos obligatorios.");
            return;
        }

        double precioNormal;
        try {
            precioNormal = Double.parseDouble(precioNormalTxt);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El precio debe ser un número válido.");
            return;
        }

        double precioEmergencia = precioNormal * 1.3;

        try {
            Connection con = Conexion.obtenerConexion();
            PreparedStatement ps = con.prepareStatement(
                    "UPDATE servicios SET nombre_servicio = ?, descripcion = ?, precio_normal = ?, precio_emergencia = ? WHERE id_servicio = ?"
            );
            ps.setString(1, nombreTxt);
            if (descripcionTxt.isEmpty()) {
                ps.setNull(2, java.sql.Types.VARCHAR);
            } else {
                ps.setString(2, descripcionTxt);
            }
            ps.setDouble(3, precioNormal);
            ps.setDouble(4, precioEmergencia);
            ps.setInt(5, idServicio);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Servicio modificado correctamente.");

            limpiar();
            cargarTabla();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al modificar: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tblServicios.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un servicio para eliminar.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este servicio?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        int idServicio = (int) tblServicios.getValueAt(filaSeleccionada, 0);

        try {
            Connection con = Conexion.obtenerConexion();
            PreparedStatement ps = con.prepareStatement("UPDATE servicios SET estado = 0 WHERE id_servicio = ?");
            ps.setInt(1, idServicio);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Servicio eliminado correctamente.");

            limpiar();
            cargarTabla();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al eliminar: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed
    private void limpiar(){
        NombreServicio.setText("");
        Descripcion.setText("");
        CostoServicio.setText("");
    }
    private void txtID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID1ActionPerformed

    private void CostoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
        try {
                    UIManager.setLookAndFeel(new FlatLightLaf());
                } catch (Exception e) {
                    e.printStackTrace();
                }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiciosPrecios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Categoria;
    private javax.swing.JTextField CostoServicio;
    private javax.swing.JLabel Desc;
    private javax.swing.JTextArea Descripcion;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton MostrarTodo;
    private javax.swing.JLabel NombreService;
    private javax.swing.JTextField NombreServicio;
    private javax.swing.JPanel Superior;
    private javax.swing.JButton btnElectronica;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnRedes;
    private javax.swing.JButton btnTelecomunicaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblServicios;
    private javax.swing.JTextField txtID1;
    // End of variables declaration//GEN-END:variables
}
