/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ReportesPagos;

import Administrador.AdministradorCajeros;
import Administrador.AdministradorDoctores;
import ConexionLogin.Conexion;
import ConexionLogin.Login;
import Servicios.ServiciosPrecios;
import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.Normalizer;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Rafael
 */
public class ReportesCampoProfesional extends javax.swing.JFrame {

    /**
     * Creates new form ReportesCampoProfesional
     */
    public ReportesCampoProfesional() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Superior = new javax.swing.JPanel();
        btnAdminCajeros = new javax.swing.JButton();
        btnListaLaboratorios = new javax.swing.JButton();
        btnReportePagos = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaReportesCampoProf = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        AgregarTecnico1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TotalPago = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DoctorSeleccionado = new javax.swing.JTextField();
        BuscadorCampo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        FechaDesde = new com.toedter.calendar.JDateChooser();
        FechaHasta = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ListaPersonal = new javax.swing.JLabel();
        TotalDetallado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        btnCalcularPagoTotal = new javax.swing.JButton();
        CategoriaBox = new javax.swing.JComboBox<>();
        ListaPersonal1 = new javax.swing.JLabel();
        FondoGris = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Superior.setBackground(new java.awt.Color(80, 35, 100));
        Superior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdminCajeros.setBackground(new java.awt.Color(33, 14, 68));
        btnAdminCajeros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdminCajeros.setForeground(new java.awt.Color(241, 241, 241));
        btnAdminCajeros.setText("Administracion de Cajeros");
        btnAdminCajeros.setBorder(null);
        btnAdminCajeros.setHorizontalAlignment(SwingConstants.LEFT);
        btnAdminCajeros.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnAdminCajeros.setIconTextGap(10);
        btnAdminCajeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdminCajerosMouseExited(evt);
            }
        });
        btnAdminCajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminCajerosActionPerformed(evt);
            }
        });
        Superior.add(btnAdminCajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 229, 60));

        btnListaLaboratorios.setBackground(new java.awt.Color(33, 14, 68));
        btnListaLaboratorios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnListaLaboratorios.setForeground(new java.awt.Color(241, 241, 241));
        btnListaLaboratorios.setText("Administracion de Doctores");
        btnListaLaboratorios.setBorder(null);
        btnListaLaboratorios.setHorizontalAlignment(SwingConstants.LEFT);
        btnListaLaboratorios.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnListaLaboratorios.setIconTextGap(10);
        btnListaLaboratorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListaLaboratoriosMouseExited(evt);
            }
        });
        btnListaLaboratorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaLaboratoriosActionPerformed(evt);
            }
        });
        Superior.add(btnListaLaboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 229, 60));

        btnReportePagos.setBackground(new java.awt.Color(33, 14, 68));
        btnReportePagos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReportePagos.setForeground(new java.awt.Color(241, 241, 241));
        btnReportePagos.setText("Reportes de Pagos");
        btnReportePagos.setBorder(null);
        btnServicios.setHorizontalAlignment(SwingConstants.LEFT);
        btnServicios.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnServicios.setIconTextGap(10);
        btnReportePagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportePagosMouseExited(evt);
            }
        });
        btnReportePagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportePagosActionPerformed(evt);
            }
        });
        Superior.add(btnReportePagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 229, 60));

        btnServicios.setBackground(new java.awt.Color(33, 14, 68));
        btnServicios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnServicios.setForeground(new java.awt.Color(241, 241, 241));
        btnServicios.setText("Servicios");
        btnServicios.setBorder(null);
        btnServicios.setHorizontalAlignment(SwingConstants.LEFT);
        btnServicios.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnServicios.setIconTextGap(10);
        btnServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnServiciosMouseExited(evt);
            }
        });
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        Superior.add(btnServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 229, 60));

        btnCerrarSesion.setBackground(new java.awt.Color(33, 14, 68));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(241, 241, 241));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setHorizontalAlignment(SwingConstants.LEFT);
        btnCerrarSesion.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnCerrarSesion.setIconTextGap(10);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        Superior.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 0, 229, 60));

        getContentPane().add(Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaReportesCampoProf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Doctor", "Campo Profesional", "Paciente", "Fecha", "Hora", "Servicio", "Precio del Servicio", "Servicio Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaReportesCampoProf.getTableHeader().setReorderingAllowed(false);
        TablaReportesCampoProf.getTableHeader().setResizingAllowed(false);
        TablaReportesCampoProf.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaReportesCampoProf.setFocusable(false);
        TablaReportesCampoProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaReportesCampoProfReportePagosMouseClicked(evt);
                TablaReportesCampoProfParaVistaPrevia(evt);
            }
        });
        jScrollPane1.setViewportView(TablaReportesCampoProf);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 1810, 710));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 194, 194)));
        jPanel1.setToolTipText("");
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarTecnico1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        AgregarTecnico1.setText("Total de Dinero por Campo Profesional");
        jPanel1.add(AgregarTecnico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setText("Campo Profesional:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));
        jPanel1.add(TotalPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 380, -1));

        jLabel4.setText("Total:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));
        jPanel1.add(DoctorSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 380, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 90, 540, 120));

        BuscadorCampo.setBackground(new java.awt.Color(233, 236, 239));
        BuscadorCampo.setBorder(null);
        BuscadorCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscadorCampoActionPerformed(evt);
            }
        });
        jPanel2.add(BuscadorCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 200, 20));
        BuscadorCampo.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                filtrarLista();
            }

            public void removeUpdate(DocumentEvent e) {
                filtrarLista();
            }

            public void changedUpdate(DocumentEvent e) {
                filtrarLista();
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_1.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 260, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(FechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, 250, -1));
        jPanel3.add(FechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 50, 250, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Desde:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Hasta:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 50, -1, -1));

        ListaPersonal.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ListaPersonal.setText("Filtradores");
        jPanel3.add(ListaPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        TotalDetallado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Total", "Detallado"}));
        TotalDetallado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalDetalladoActionPerformed(evt);
            }
        });
        jPanel3.add(TotalDetallado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 220, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Campo Profesional: ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        Buscar.setBackground(new java.awt.Color(29, 41, 57));
        Buscar.setForeground(new java.awt.Color(255, 255, 255));
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel3.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 90, 110, -1));

        btnCalcularPagoTotal.setText("Calcular Monto");
        btnCalcularPagoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularPagoTotalActionPerformed(evt);
            }
        });
        jPanel3.add(btnCalcularPagoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 90, 130, -1));

        CategoriaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        jPanel3.add(CategoriaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 190, -1));
        cargarCategoriaBox();

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1270, 120));

        ListaPersonal1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        ListaPersonal1.setText("Reporte de Pagos Doctor");
        jPanel2.add(ListaPersonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1880, 980));

        FondoGris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Background.jpg"))); // NOI18N
        getContentPane().add(FondoGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarCategoriaBox() {
    CategoriaBox.removeAllItems(); // Limpia el combo
    CategoriaBox.addItem(""); // Agrega opción vacía al inicio (no seleccionado)

    String sql = """
        SELECT DISTINCT
            CASE 
                WHEN categoria_profesional = 'Otro' THEN categoria_profesional_otro
                ELSE especialidad
            END AS campo_profesional
        FROM medicos
        WHERE 
            (categoria_profesional = 'Otro' AND categoria_profesional_otro IS NOT NULL AND categoria_profesional_otro <> '')
            OR
            (categoria_profesional != 'Otro' AND especialidad IS NOT NULL AND especialidad <> '')
    """;

    try (Connection con = Conexion.obtenerConexion();
         PreparedStatement ps = con.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            String campo = rs.getString("campo_profesional");
            CategoriaBox.addItem(campo);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al cargar campo profesional: " + e.getMessage());
        e.printStackTrace();
    }
}
    
        private void cargaTablaReporte() {
    DefaultTableModel modelo = new DefaultTableModel();
    String seleccion = (String) TotalDetallado.getSelectedItem();

    if (seleccion.equals("Total")) {
        modelo.setColumnIdentifiers(new Object[]{
            "ID", "Doctor", "Campo Profesional", "Paciente", "Fecha", "Hora", "Servicio", "Servicio Total"
        });
    } else if (seleccion.equals("Detallado")) {
        modelo.setColumnIdentifiers(new Object[]{
            "ID", "Doctor", "Campo Profesional", "Paciente", "Fecha", "Hora", "Servicio", "Precio del Servicio"
        });
    }

    String sqlTotal = """
        SELECT 
            a.id_afiche, 
            CONCAT(m.nombre, ' ', m.apellido) AS doctor,
            CASE
                WHEN m.especialidad IS NOT NULL AND m.especialidad <> '' THEN m.especialidad
                WHEN m.categoria_profesional_otro IS NOT NULL AND m.categoria_profesional_otro <> '' THEN m.categoria_profesional_otro
                ELSE m.categoria_profesional
            END AS campo_profesional,
            CONCAT(a.nombre_paciente, ' ', a.apellido_paciente) AS paciente,
            a.fecha_atencion,
            a.hora_atencion,
            a.precio_total AS servicio_total,
            COUNT(da.id_servicio) AS cantidad_servicios
        FROM afiches a
        JOIN medicos m ON m.id_medico = a.id_medico
        LEFT JOIN detalle_afiche da ON da.id_afiche = a.id_afiche
        GROUP BY a.id_afiche, m.nombre, m.apellido, m.especialidad, m.categoria_profesional, m.categoria_profesional_otro,
                 a.nombre_paciente, a.apellido_paciente, a.fecha_atencion, a.hora_atencion, a.precio_total
        ORDER BY a.id_afiche
    """;

    String sqlDetallado = """
        SELECT 
            a.id_afiche, 
            CONCAT(m.nombre, ' ', m.apellido) AS doctor,
            CASE
                WHEN m.especialidad IS NOT NULL AND m.especialidad <> '' THEN m.especialidad
                WHEN m.categoria_profesional_otro IS NOT NULL AND m.categoria_profesional_otro <> '' THEN m.categoria_profesional_otro
                ELSE m.categoria_profesional
            END AS campo_profesional,
            CONCAT(a.nombre_paciente, ' ', a.apellido_paciente) AS paciente,
            a.fecha_atencion,
            a.hora_atencion,
            s.nombre_servicio AS servicio,
            CASE da.tipo_precio
                WHEN 'normal' THEN s.precio_normal
                WHEN 'emergencia' THEN s.precio_emergencia
            END AS precio_servicio
        FROM afiches a
        JOIN medicos m ON m.id_medico = a.id_medico
        JOIN detalle_afiche da ON da.id_afiche = a.id_afiche
        JOIN servicios s ON s.id_servicio = da.id_servicio
        ORDER BY a.id_afiche
    """;

    String sql = seleccion.equals("Total") ? sqlTotal : sqlDetallado;

    try (Connection con = Conexion.obtenerConexion();
         PreparedStatement ps = con.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            if (seleccion.equals("Total")) {
                int cantidadServicios = rs.getInt("cantidad_servicios");
                String descripcion = (cantidadServicios == 1) ? "Único servicio" : "Varios servicios";

                modelo.addRow(new Object[]{
                    rs.getInt("id_afiche"),
                    rs.getString("doctor"),
                    rs.getString("campo_profesional"),
                    rs.getString("paciente"),
                    rs.getTimestamp("fecha_atencion").toLocalDateTime().toLocalDate(),
                    rs.getString("hora_atencion"),
                    descripcion,
                    rs.getDouble("servicio_total")
                });
            } else {
                modelo.addRow(new Object[]{
                    rs.getInt("id_afiche"),
                    rs.getString("doctor"),
                    rs.getString("campo_profesional"),
                    rs.getString("paciente"),
                    rs.getTimestamp("fecha_atencion").toLocalDateTime().toLocalDate(),
                    rs.getString("hora_atencion"),
                    rs.getString("servicio"),
                    rs.getDouble("precio_servicio")
                });
            }
        }

        TablaReportesCampoProf.setModel(modelo);

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error al cargar afiches: " + ex.getMessage());
        ex.printStackTrace();
    }
}

    private String quitarTildes(String texto) {
        if (texto == null) {
            return "";
        }
        texto = Normalizer.normalize(texto, Normalizer.Form.NFD);
        return texto.replaceAll("\\p{InCombiningDiacriticalMarks}+", "");
    }

    private void filtrarLista() {
        String texto = BuscadorCampo.getText();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(TablaReportesCampoProf.getModel());
        TablaReportesCampoProf.setRowSorter(sorter);

        // Aplica el filtro solo a la columna "Doctor", que está en el índice 1
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto, 1));
    }
    private void btnAdminCajerosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminCajerosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminCajerosMouseExited

    private void btnAdminCajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCajerosActionPerformed
        AdministradorCajeros admincaj = new AdministradorCajeros();
        admincaj.setLocationRelativeTo(null);
        admincaj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminCajerosActionPerformed

    private void btnListaLaboratoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaLaboratoriosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaLaboratoriosMouseExited

    private void btnListaLaboratoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaLaboratoriosActionPerformed
        AdministradorDoctores admindoc = new AdministradorDoctores();
        admindoc.setLocationRelativeTo(null);
        admindoc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListaLaboratoriosActionPerformed

    private void btnReportePagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportePagosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportePagosMouseExited

    private void btnReportePagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportePagosActionPerformed

    }//GEN-LAST:event_btnReportePagosActionPerformed

    private void btnServiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServiciosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServiciosMouseExited

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        ServiciosPrecios serv = new ServiciosPrecios();
        serv.setLocationRelativeTo(null);
        serv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited

    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Login cerrar = new Login();
        cerrar.setLocationRelativeTo(null);
        cerrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void TablaReportesCampoProfReportePagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaReportesCampoProfReportePagosMouseClicked

    }//GEN-LAST:event_TablaReportesCampoProfReportePagosMouseClicked

    private void BuscadorCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscadorCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscadorCampoActionPerformed

    private void TotalDetalladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalDetalladoActionPerformed

    }//GEN-LAST:event_TotalDetalladoActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed

    }//GEN-LAST:event_BuscarActionPerformed

    private void btnCalcularPagoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPagoTotalActionPerformed

    }//GEN-LAST:event_btnCalcularPagoTotalActionPerformed

    private void TablaReportesCampoProfParaVistaPrevia(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaReportesCampoProfParaVistaPrevia

    }//GEN-LAST:event_TablaReportesCampoProfParaVistaPrevia

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportesCampoProfesional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportesCampoProfesional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportesCampoProfesional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportesCampoProfesional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportesCampoProfesional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarTecnico1;
    private javax.swing.JTextField BuscadorCampo;
    private javax.swing.JButton Buscar;
    private javax.swing.JComboBox<String> CategoriaBox;
    private javax.swing.JTextField DoctorSeleccionado;
    private com.toedter.calendar.JDateChooser FechaDesde;
    private com.toedter.calendar.JDateChooser FechaHasta;
    private javax.swing.JLabel FondoGris;
    private javax.swing.JLabel ListaPersonal;
    private javax.swing.JLabel ListaPersonal1;
    private javax.swing.JPanel Superior;
    private javax.swing.JTable TablaReportesCampoProf;
    private javax.swing.JComboBox<String> TotalDetallado;
    private javax.swing.JTextField TotalPago;
    private javax.swing.JButton btnAdminCajeros;
    private javax.swing.JButton btnCalcularPagoTotal;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnListaLaboratorios;
    private javax.swing.JButton btnReportePagos;
    private javax.swing.JButton btnServicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
