/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ReportesPagos;

import Administrador.AdministradorCajeros;
import Administrador.AdministradorDoctores;
import ConexionLogin.Conexion;
import ConexionLogin.Login;
import Servicios.ServiciosPrecios;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.Normalizer;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Rafael
 */
public class ReportesCampoProfesional extends javax.swing.JFrame {

    /**
     * Creates new form ReportesCampoProfesional
     */
    public ReportesCampoProfesional() {
        initComponents();
        aplicarColorFilasAlternadas(TablaReportesCampoProf);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        TotalDetallado.setSelectedItem("Total");
        cargaTablaReporte();
        cargarCategoriaBox();
    }
    private void aplicarColorFilasAlternadas(JTable tabla) {
        TableCellRenderer renderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                if (isSelected) {
                    setBackground(table.getSelectionBackground());
                    setForeground(table.getSelectionForeground());
                } else {
                    if (row % 2 == 0) {
                        setBackground(Color.WHITE);
                        setForeground(Color.BLACK);
                    } else {
                        setBackground(new Color(240, 240, 240));
                        setForeground(Color.BLACK);
                    }
                }

                return this;
            }
        };

        for (int i = 0; i < tabla.getColumnCount(); i++) {
            tabla.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Superior = new javax.swing.JPanel();
        btnAdminCajeros = new javax.swing.JButton();
        btnListaLaboratorios = new javax.swing.JButton();
        btnReporteEspeci = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnReportePagos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaReportesCampoProf = new javax.swing.JTable();
        ListaPersonal1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TotalDetallado = new javax.swing.JComboBox<>();
        CategoriaBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Buscar = new javax.swing.JButton();
        FechaDesde = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        FechaHasta = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TotalPago = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Especialidad = new javax.swing.JTextField();
        btnCalcularPagoTotal = new javax.swing.JButton();
        FondoGris = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Superior.setBackground(new java.awt.Color(80, 35, 100));
        Superior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdminCajeros.setBackground(new java.awt.Color(33, 14, 68));
        btnAdminCajeros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdminCajeros.setForeground(new java.awt.Color(241, 241, 241));
        btnAdminCajeros.setText("Administracion de Cajeros");
        btnAdminCajeros.setBorder(null);
        btnAdminCajeros.setHorizontalAlignment(SwingConstants.LEFT);
        btnAdminCajeros.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnAdminCajeros.setIconTextGap(10);
        btnAdminCajeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdminCajerosMouseExited(evt);
            }
        });
        btnAdminCajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminCajerosActionPerformed(evt);
            }
        });
        Superior.add(btnAdminCajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 229, 60));

        btnListaLaboratorios.setBackground(new java.awt.Color(33, 14, 68));
        btnListaLaboratorios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnListaLaboratorios.setForeground(new java.awt.Color(241, 241, 241));
        btnListaLaboratorios.setText("Administracion de Doctores");
        btnListaLaboratorios.setBorder(null);
        btnListaLaboratorios.setHorizontalAlignment(SwingConstants.LEFT);
        btnListaLaboratorios.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnListaLaboratorios.setIconTextGap(10);
        btnListaLaboratorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListaLaboratoriosMouseExited(evt);
            }
        });
        btnListaLaboratorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaLaboratoriosActionPerformed(evt);
            }
        });
        Superior.add(btnListaLaboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 229, 60));

        btnReporteEspeci.setBackground(new java.awt.Color(33, 14, 68));
        btnReporteEspeci.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReporteEspeci.setForeground(new java.awt.Color(241, 241, 241));
        btnReporteEspeci.setText("Reportes de Especialidades");
        btnReporteEspeci.setBorder(null);
        btnServicios.setHorizontalAlignment(SwingConstants.LEFT);
        btnServicios.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnServicios.setIconTextGap(10);
        btnReporteEspeci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteEspeciMouseExited(evt);
            }
        });
        btnReporteEspeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteEspeciActionPerformed(evt);
            }
        });
        Superior.add(btnReporteEspeci, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 229, 60));

        btnServicios.setBackground(new java.awt.Color(33, 14, 68));
        btnServicios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnServicios.setForeground(new java.awt.Color(241, 241, 241));
        btnServicios.setText("Servicios");
        btnServicios.setBorder(null);
        btnServicios.setHorizontalAlignment(SwingConstants.LEFT);
        btnServicios.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnServicios.setIconTextGap(10);
        btnServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnServiciosMouseExited(evt);
            }
        });
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        Superior.add(btnServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 229, 60));

        btnCerrarSesion.setBackground(new java.awt.Color(33, 14, 68));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(241, 241, 241));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setHorizontalAlignment(SwingConstants.LEFT);
        btnCerrarSesion.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnCerrarSesion.setIconTextGap(10);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        Superior.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 0, 229, 60));

        btnReportePagos.setBackground(new java.awt.Color(33, 14, 68));
        btnReportePagos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReportePagos.setForeground(new java.awt.Color(241, 241, 241));
        btnReportePagos.setText("Reportes de Pagos");
        btnReportePagos.setBorder(null);
        btnServicios.setHorizontalAlignment(SwingConstants.LEFT);
        btnServicios.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnServicios.setIconTextGap(10);
        btnReportePagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportePagosMouseExited(evt);
            }
        });
        btnReportePagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportePagosActionPerformed(evt);
            }
        });
        Superior.add(btnReportePagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 229, 60));

        getContentPane().add(Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaReportesCampoProf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Doctor", "Campo Profesional", "Fecha", "Servicio Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaReportesCampoProf.getTableHeader().setReorderingAllowed(false);
        TablaReportesCampoProf.getTableHeader().setResizingAllowed(false);
        TablaReportesCampoProf.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaReportesCampoProf.setFocusable(false);
        TablaReportesCampoProf.setAutoCreateRowSorter(false);
        TablaReportesCampoProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaReportesCampoProfReportePagosMouseClicked(evt);
                TablaReportesCampoProfParaVistaPrevia(evt);
            }
        });
        jScrollPane1.setViewportView(TablaReportesCampoProf);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 1820, 730));

        ListaPersonal1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        ListaPersonal1.setText("Reporte de Especialidades");
        jPanel2.add(ListaPersonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 280, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Tipo de ficha:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        TotalDetallado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos"}));
        TotalDetallado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalDetalladoActionPerformed(evt);
            }
        });
        jPanel5.add(TotalDetallado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 15, 260, 30));

        CategoriaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        jPanel5.add(CategoriaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 15, 330, 30));
        cargarCategoriaBox();

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Campo Profesional: ");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 1250, 61));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscar.setBackground(new java.awt.Color(80, 35, 100));
        Buscar.setForeground(new java.awt.Color(255, 255, 255));
        Buscar.setText("Aplicar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel3.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 15, 110, 30));
        jPanel3.add(FechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 15, 260, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Desde:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));
        jPanel3.add(FechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 15, 250, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Hasta:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, 40));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 15, 110, 30));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 70, 1308, 60));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1310, 130));
        jPanel4.getAccessibleContext().setAccessibleName("");
        jPanel4.getAccessibleContext().setAccessibleDescription("");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reporte de Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Especialidad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        TotalPago.setEditable(false);
        TotalPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPagoActionPerformed(evt);
            }
        });
        jPanel1.add(TotalPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 400, 30));

        jLabel4.setText("Total:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        Especialidad.setEditable(false);
        jPanel1.add(Especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 400, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 50, 520, 130));
        jPanel1.getAccessibleContext().setAccessibleName("Campo Profesional");

        btnCalcularPagoTotal.setBackground(new java.awt.Color(0, 204, 204));
        btnCalcularPagoTotal.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularPagoTotal.setText("Calcular Pago");
        btnCalcularPagoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularPagoTotalActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalcularPagoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 190, 110, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1880, 980));

        FondoGris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Background.jpg"))); // NOI18N
        getContentPane().add(FondoGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarCategoriaBox() {
    CategoriaBox.removeAllItems();
    CategoriaBox.addItem("Todos");

    String sql = """
        SELECT DISTINCT
            CASE 
                WHEN categoria_profesional = 'Otro' THEN categoria_profesional_otro
                ELSE especialidad
            END AS campo_profesional
        FROM medicos
        WHERE 
            (categoria_profesional = 'Otro' AND categoria_profesional_otro IS NOT NULL AND categoria_profesional_otro <> '')
            OR
            (categoria_profesional != 'Otro' AND especialidad IS NOT NULL AND especialidad <> '')
    """;

    try (Connection con = Conexion.obtenerConexion();
         PreparedStatement ps = con.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        Map<String, String> categoriasUnicas = new TreeMap<>();

        while (rs.next()) {
            String campoOriginal = rs.getString("campo_profesional");
            if (campoOriginal != null && !campoOriginal.trim().isEmpty()) {
                String claveNormalizada = quitarTildes(campoOriginal.trim().toLowerCase());
                if (!categoriasUnicas.containsKey(claveNormalizada)) {
                    categoriasUnicas.put(claveNormalizada, campoOriginal.trim());
                }
            }
        }

        for (String valor : categoriasUnicas.values()) {
            CategoriaBox.addItem(valor);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al cargar campo profesional: " + e.getMessage());
        e.printStackTrace();
    }
}


private void cargaTablaReporte() {
    DefaultTableModel modelo = new DefaultTableModel(
        new Object[][] {},
        new String[] {"ID", "Doctor", "Campo Profesional", "Fecha", "Servicio Total"}
    ) {
        public boolean isCellEditable(int row, int col) { return false; }
        public Class<?> getColumnClass(int col) {
            return (col == 0) ? Integer.class : String.class;
        }
    };

    String sql = """
        SELECT 
            a.id_afiche, 
            CONCAT(m.nombre, ' ', m.apellido) AS doctor,
            COALESCE(m.especialidad, m.categoria_profesional_otro) AS campo_profesional,
            a.fecha_atencion,
            a.precio_total AS servicio_total
        FROM afiches a
        JOIN medicos m ON m.id_medico = a.id_medico
        ORDER BY a.id_afiche
    """;

    try (Connection con = Conexion.obtenerConexion();
         PreparedStatement ps = con.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            String totalFormateado = "Bs. " + String.format("%.2f", rs.getDouble("servicio_total"));

            modelo.addRow(new Object[] {
                rs.getInt("id_afiche"),
                rs.getString("doctor"),
                rs.getString("campo_profesional"),
                rs.getDate("fecha_atencion"),
                totalFormateado
            });
        }

        TablaReportesCampoProf.setModel(modelo);

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error al cargar afiches: " + ex.getMessage());
        ex.printStackTrace();
    }
}

  
    private void btnAdminCajerosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminCajerosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminCajerosMouseExited

    private void btnAdminCajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCajerosActionPerformed
        AdministradorCajeros admincaj = new AdministradorCajeros();
        admincaj.setLocationRelativeTo(null);
        admincaj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminCajerosActionPerformed

    private void btnListaLaboratoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaLaboratoriosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaLaboratoriosMouseExited

    private void btnListaLaboratoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaLaboratoriosActionPerformed
        AdministradorDoctores admindoc = new AdministradorDoctores();
        admindoc.setLocationRelativeTo(null);
        admindoc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListaLaboratoriosActionPerformed

    private void btnReporteEspeciMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteEspeciMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteEspeciMouseExited

    private void btnReporteEspeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteEspeciActionPerformed
        
    }//GEN-LAST:event_btnReporteEspeciActionPerformed

    private void btnServiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServiciosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServiciosMouseExited

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        ServiciosPrecios serv = new ServiciosPrecios();
        serv.setLocationRelativeTo(null);
        serv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited

    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Login cerrar = new Login();
        cerrar.setLocationRelativeTo(null);
        cerrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void TablaReportesCampoProfReportePagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaReportesCampoProfReportePagosMouseClicked

    }//GEN-LAST:event_TablaReportesCampoProfReportePagosMouseClicked

    private void TablaReportesCampoProfParaVistaPrevia(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaReportesCampoProfParaVistaPrevia

    }//GEN-LAST:event_TablaReportesCampoProfParaVistaPrevia

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
    String categoriaSeleccionada = (String) CategoriaBox.getSelectedItem();
    Especialidad.setText(categoriaSeleccionada);
    Date desde = FechaDesde.getDate();
    Date hasta = FechaHasta.getDate();

    if (desde == null || hasta == null) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar ambas fechas (Desde y Hasta).");
        return;
    }

    if (desde.after(hasta)) {
        JOptionPane.showMessageDialog(this, "La fecha 'Desde' no puede ser mayor que la fecha 'Hasta'.");
        return;
    }

    Calendar calDesde = Calendar.getInstance();
    calDesde.setTime(desde);
    calDesde.set(Calendar.HOUR_OF_DAY, 0);
    calDesde.set(Calendar.MINUTE, 0);
    calDesde.set(Calendar.SECOND, 0);
    calDesde.set(Calendar.MILLISECOND, 0);
    final Date desdeFinal = calDesde.getTime();

    Calendar calHasta = Calendar.getInstance();
    calHasta.setTime(hasta);
    calHasta.set(Calendar.HOUR_OF_DAY, 23);
    calHasta.set(Calendar.MINUTE, 59);
    calHasta.set(Calendar.SECOND, 59);
    calHasta.set(Calendar.MILLISECOND, 999);
    final Date hastaFinal = calHasta.getTime();

    TableRowSorter<TableModel> sorter = new TableRowSorter<>(TablaReportesCampoProf.getModel());
    TablaReportesCampoProf.setRowSorter(sorter);

    DateFormat df = new SimpleDateFormat("yyyy-MM-dd");

    List<RowFilter<Object, Object>> filtros = new ArrayList<>();

    if (categoriaSeleccionada != null && !categoriaSeleccionada.equals("Todos") && !categoriaSeleccionada.trim().isEmpty()) {
        final String filtroSinTildes = quitarTildes(categoriaSeleccionada.toLowerCase());

        filtros.add(new RowFilter<Object, Object>() {
            @Override
            public boolean include(Entry<? extends Object, ? extends Object> entry) {
                String valorCelda = entry.getStringValue(2);
                if (valorCelda == null) return false;

                String valorSinTildes = quitarTildes(valorCelda.toLowerCase());
                return valorSinTildes.equals(filtroSinTildes);
            }
        });
    }

    filtros.add(new RowFilter<Object, Object>() {
        @Override
        public boolean include(Entry<? extends Object, ? extends Object> entry) {
            try {
                String fechaTexto = entry.getStringValue(3); // columna 3 = Fecha
                Date fecha = df.parse(fechaTexto);
                return !fecha.before(desdeFinal) && !fecha.after(hastaFinal);
            } catch (ParseException e) {
                return false;
            }
        }
    });

    sorter.setRowFilter(RowFilter.andFilter(filtros));
    }//GEN-LAST:event_BuscarActionPerformed
    public static String quitarTildes(String texto) {
        if (texto == null) {
            return null;
        }
        String normalized = Normalizer.normalize(texto, Normalizer.Form.NFD);
        return normalized.replaceAll("\\p{InCombiningDiacriticalMarks}+", "");
    }
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        CategoriaBox.setSelectedIndex(0);
        FechaDesde.setDate(null);
        FechaHasta.setDate(null);
        TablaReportesCampoProf.setRowSorter(null);
        TotalPago.setText("");
        Especialidad.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void TotalPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPagoActionPerformed

    private void btnReportePagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportePagosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportePagosMouseExited

    private void btnReportePagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportePagosActionPerformed
        ReportespagarMedico reportpag = new ReportespagarMedico();
        reportpag.setLocationRelativeTo(null);
        reportpag.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReportePagosActionPerformed

    private void TotalDetalladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalDetalladoActionPerformed

    }//GEN-LAST:event_TotalDetalladoActionPerformed

    private void btnCalcularPagoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPagoTotalActionPerformed
        TableModel modelo = TablaReportesCampoProf.getModel();
        double sumaTotal = 0;

        int colPrecio = -1;

        for (int i = 0; i < modelo.getColumnCount(); i++) {
            if (modelo.getColumnName(i).equalsIgnoreCase("Servicio Total")) {
                colPrecio = i;
                break;
            }
        }

        if (colPrecio == -1) {
            JOptionPane.showMessageDialog(this, "No se encontró la columna de 'Servicio Total'.");
            return;
        }

        for (int i = 0; i < TablaReportesCampoProf.getRowCount(); i++) {
            int rowIndex = TablaReportesCampoProf.convertRowIndexToModel(i);
            Object val = modelo.getValueAt(rowIndex, colPrecio);

            if (val != null) {
                try {
                    String strVal = val.toString()
                            .replace("Bs.", "")
                            .replace("Bs", "")
                            .replace(",", ".")
                            .trim();
                    sumaTotal += Double.parseDouble(strVal);
                } catch (NumberFormatException e) {
                    e.printStackTrace(); 
                }
            }
        }

        String totalFormateado = "Bs. " + String.format("%.2f", sumaTotal);
        JOptionPane.showMessageDialog(this, "Pago total: " + totalFormateado);
        TotalPago.setText(totalFormateado);
    }//GEN-LAST:event_btnCalcularPagoTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e){
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportesCampoProfesional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JComboBox<String> CategoriaBox;
    private javax.swing.JTextField Especialidad;
    private com.toedter.calendar.JDateChooser FechaDesde;
    private com.toedter.calendar.JDateChooser FechaHasta;
    private javax.swing.JLabel FondoGris;
    private javax.swing.JLabel ListaPersonal1;
    private javax.swing.JPanel Superior;
    private javax.swing.JTable TablaReportesCampoProf;
    private javax.swing.JComboBox<String> TotalDetallado;
    private javax.swing.JTextField TotalPago;
    private javax.swing.JButton btnAdminCajeros;
    private javax.swing.JButton btnCalcularPagoTotal;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListaLaboratorios;
    private javax.swing.JButton btnReporteEspeci;
    private javax.swing.JButton btnReportePagos;
    private javax.swing.JButton btnServicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
