/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ReportesPagos;

import Administrador.AdministradorCajeros;
import Administrador.AdministradorDoctores;
import ConexionLogin.Conexion;
import ConexionLogin.Login;
import Servicios.ServiciosPrecios;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.Normalizer;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Rafael
 */
public class ReportespagarMedico extends javax.swing.JFrame {

    /**
     * Creates new form ReportesMedicos
     */// Referencias a las columnas (fuera del método si quieres reutilizarlas)


    
    public ReportespagarMedico() {
        initComponents();

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        TotalDetallado.setSelectedItem("Total");
        cargaTablaReporte();
        aplicarColorFilasAlternadas(TablaReportes);
    }

        private void aplicarColorFilasAlternadas(JTable tabla) {
        TableCellRenderer renderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                if (isSelected) {
                    setBackground(table.getSelectionBackground());
                    setForeground(table.getSelectionForeground());
                } else {
                    if (row % 2 == 0) {
                        setBackground(Color.WHITE);
                        setForeground(Color.BLACK);
                    } else {
                        setBackground(new Color(240, 240, 240));
                        setForeground(Color.BLACK);
                    }
                }

                return this;
            }
        };

        for (int i = 0; i < tabla.getColumnCount(); i++) {
            tabla.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Superior = new javax.swing.JPanel();
        btnAdminCajeros = new javax.swing.JButton();
        btnListaLaboratorios = new javax.swing.JButton();
        btnReportePagos = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaReportes = new javax.swing.JTable();
        ListaPersonal1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TotalPago = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DoctorSeleccionado = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BuscadorDoctores = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        NombreDoctor = new javax.swing.JTextField();
        TotalDetallado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Buscar = new javax.swing.JButton();
        FechaDesde = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        FechaHasta = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnCalcularPagoTotal = new javax.swing.JButton();
        FondoGris = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Superior.setBackground(new java.awt.Color(80, 35, 100));
        Superior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdminCajeros.setBackground(new java.awt.Color(33, 14, 68));
        btnAdminCajeros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdminCajeros.setForeground(new java.awt.Color(241, 241, 241));
        btnAdminCajeros.setText("Administracion de Cajeros");
        btnAdminCajeros.setBorder(null);
        btnAdminCajeros.setHorizontalAlignment(SwingConstants.LEFT);
        btnAdminCajeros.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnAdminCajeros.setIconTextGap(10);
        btnAdminCajeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdminCajerosMouseExited(evt);
            }
        });
        btnAdminCajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminCajerosActionPerformed(evt);
            }
        });
        Superior.add(btnAdminCajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 229, 60));

        btnListaLaboratorios.setBackground(new java.awt.Color(33, 14, 68));
        btnListaLaboratorios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnListaLaboratorios.setForeground(new java.awt.Color(241, 241, 241));
        btnListaLaboratorios.setText("Administracion de Doctores");
        btnListaLaboratorios.setBorder(null);
        btnListaLaboratorios.setHorizontalAlignment(SwingConstants.LEFT);
        btnListaLaboratorios.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnListaLaboratorios.setIconTextGap(10);
        btnListaLaboratorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListaLaboratoriosMouseExited(evt);
            }
        });
        btnListaLaboratorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaLaboratoriosActionPerformed(evt);
            }
        });
        Superior.add(btnListaLaboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 229, 60));

        btnReportePagos.setBackground(new java.awt.Color(33, 14, 68));
        btnReportePagos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReportePagos.setForeground(new java.awt.Color(241, 241, 241));
        btnReportePagos.setText("Reportes de Pagos");
        btnReportePagos.setBorder(null);
        btnServicios.setHorizontalAlignment(SwingConstants.LEFT);
        btnServicios.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnServicios.setIconTextGap(10);
        btnReportePagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportePagosMouseExited(evt);
            }
        });
        btnReportePagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportePagosActionPerformed(evt);
            }
        });
        Superior.add(btnReportePagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 229, 60));

        btnServicios.setBackground(new java.awt.Color(33, 14, 68));
        btnServicios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnServicios.setForeground(new java.awt.Color(241, 241, 241));
        btnServicios.setText("Servicios");
        btnServicios.setBorder(null);
        btnServicios.setHorizontalAlignment(SwingConstants.LEFT);
        btnServicios.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnServicios.setIconTextGap(10);
        btnServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnServiciosMouseExited(evt);
            }
        });
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        Superior.add(btnServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 229, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrarsesion.png"))); // NOI18N
        Superior.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1890, 0, 20, 60));

        btnCerrarSesion.setBackground(new java.awt.Color(33, 14, 68));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(241, 241, 241));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setHorizontalAlignment(SwingConstants.LEFT);
        btnCerrarSesion.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnCerrarSesion.setIconTextGap(10);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        Superior.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1740, 0, 180, 60));

        getContentPane().add(Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Doctor", "Campo Profesional", "Paciente", "Fecha", "Hora", "Servicio", "Precio del Servicio", "Servicio Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaReportes.getTableHeader().setReorderingAllowed(false);
        TablaReportes.getTableHeader().setResizingAllowed(false);
        TablaReportes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaReportes.setFocusable(false);
        TablaReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportePagosMouseClicked(evt);
                ReporteVistaPreviaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaReportes);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 1840, 730));

        ListaPersonal1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        ListaPersonal1.setText("Reportes de Pagos");
        jPanel2.add(ListaPersonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reporte de Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Doctor:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        TotalPago.setEditable(false);
        TotalPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPagoActionPerformed(evt);
            }
        });
        jPanel1.add(TotalPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 400, 30));

        jLabel4.setText("Total:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        DoctorSeleccionado.setEditable(false);
        jPanel1.add(DoctorSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 400, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 50, 520, 130));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        BuscadorDoctores.setBackground(new java.awt.Color(233, 236, 239));
        BuscadorDoctores.setBorder(null);
        BuscadorDoctores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscadorDoctoresActionPerformed(evt);
            }
        });
        jPanel4.add(BuscadorDoctores, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, 40));
        BuscadorDoctores.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                filtrarLista();
            }

            public void removeUpdate(DocumentEvent e) {
                filtrarLista();
            }

            public void changedUpdate(DocumentEvent e) {
                filtrarLista();
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_1.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 40));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tipo de ficha:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        NombreDoctor.setEditable(false);
        NombreDoctor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        NombreDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreDoctorActionPerformed(evt);
            }
        });
        jPanel5.add(NombreDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 15, 250, 30));

        TotalDetallado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Total", "Detallado"}));
        TotalDetallado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalDetalladoActionPerformed(evt);
            }
        });
        jPanel5.add(TotalDetallado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 15, 260, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Doctor seleccionado:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 1100, 61));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscar.setBackground(new java.awt.Color(33, 14, 68));
        Buscar.setForeground(new java.awt.Color(255, 255, 255));
        Buscar.setText("Aplicar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel3.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 15, 110, 30));
        jPanel3.add(FechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 15, 260, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Desde:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));
        jPanel3.add(FechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 15, 250, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Hasta:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, 40));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 15, 110, 30));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 70, 1308, 60));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1310, 130));

        btnCalcularPagoTotal.setBackground(new java.awt.Color(0, 204, 204));
        btnCalcularPagoTotal.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularPagoTotal.setText("Calcular Pago");
        btnCalcularPagoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularPagoTotalActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalcularPagoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 190, 110, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1880, 980));

        FondoGris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Background.jpg"))); // NOI18N
        getContentPane().add(FondoGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
private void cargaTablaReporte() {
    String seleccion = (String) TotalDetallado.getSelectedItem();

    DefaultTableModel modelo;

    if (seleccion.equals("Total")) {
        modelo = new DefaultTableModel(
            new Object[][] {},
            new String[] {"ID", "Doctor", "Campo Profesional", "Paciente", "Fecha", "Hora", "Servicio", "Servicio Total"}
        ) {
            public boolean isCellEditable(int row, int col) { return false; }
            public Class<?> getColumnClass(int col) {
                if (col == 0) return Integer.class;
                return String.class; // ahora todo es String por el "Bs."
            }
        };
    } else {
        modelo = new DefaultTableModel(
            new Object[][] {},
            new String[] {"ID", "Doctor", "Campo Profesional", "Paciente", "Fecha", "Hora", "Servicio", "Precio del Servicio"}
        ) {
            public boolean isCellEditable(int row, int col) { return false; }
            public Class<?> getColumnClass(int col) {
                if (col == 0) return Integer.class;
                return String.class; // también todo String por "Bs."
            }
        };
    }

    String sqlTotal = """
        SELECT 
            a.id_afiche, 
            CONCAT(m.nombre, ' ', m.apellido) AS doctor,
            COALESCE(m.especialidad, m.categoria_profesional_otro) AS campo_profesional,
            CONCAT(a.nombre_paciente, ' ', a.apellido_paciente) AS paciente,
            a.fecha_atencion,
            a.hora_atencion,
            a.precio_total AS servicio_total,
            COUNT(da.id_servicio) AS cantidad_servicios
        FROM afiches a
        JOIN medicos m ON m.id_medico = a.id_medico
        LEFT JOIN detalle_afiche da ON da.id_afiche = a.id_afiche
        GROUP BY a.id_afiche, m.nombre, m.apellido, m.especialidad, m.categoria_profesional_otro, a.nombre_paciente, a.apellido_paciente, a.fecha_atencion, a.hora_atencion, a.precio_total
        ORDER BY a.id_afiche
    """;

    String sqlDetallado = """
        SELECT 
            a.id_afiche, 
            CONCAT(m.nombre, ' ', m.apellido) AS doctor,
            COALESCE(m.especialidad, m.categoria_profesional_otro) AS campo_profesional,
            CONCAT(a.nombre_paciente, ' ', a.apellido_paciente) AS paciente,
            a.fecha_atencion,
            a.hora_atencion,
            s.nombre_servicio AS servicio,
            CASE da.tipo_precio
                WHEN 'normal' THEN s.precio_normal
                WHEN 'emergencia' THEN s.precio_emergencia
            END AS precio_servicio
        FROM afiches a
        JOIN medicos m ON m.id_medico = a.id_medico
        JOIN detalle_afiche da ON da.id_afiche = a.id_afiche
        JOIN servicios s ON s.id_servicio = da.id_servicio
        ORDER BY a.id_afiche
    """;

    String sql = seleccion.equals("Total") ? sqlTotal : sqlDetallado;

    try (Connection con = Conexion.obtenerConexion();
         PreparedStatement ps = con.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            if (seleccion.equals("Total")) {
                int cantidadServicios = rs.getInt("cantidad_servicios");
                String descripcion = (cantidadServicios == 1) ? "Único servicio" : "Varios servicios";

                // Formatear el precio total con Bs. y 2 decimales
                String totalFormateado = "Bs. " + String.format("%.2f", rs.getDouble("servicio_total"));

                modelo.addRow(new Object[]{
                    rs.getInt("id_afiche"),
                    rs.getString("doctor"),
                    rs.getString("campo_profesional"),
                    rs.getString("paciente"),
                    rs.getTimestamp("fecha_atencion").toLocalDateTime().toLocalDate(),
                    rs.getString("hora_atencion"),
                    descripcion,
                    totalFormateado
                });
            } else {
                // Formatear el precio de servicio con Bs. y 2 decimales
                String precioFormateado = "Bs. " + String.format("%.2f", rs.getDouble("precio_servicio"));

                modelo.addRow(new Object[]{
                    rs.getInt("id_afiche"),
                    rs.getString("doctor"),
                    rs.getString("campo_profesional"),
                    rs.getString("paciente"),
                    rs.getTimestamp("fecha_atencion").toLocalDateTime().toLocalDate(),
                    rs.getString("hora_atencion"),
                    rs.getString("servicio"),
                    precioFormateado
                });
            }
        }

        TablaReportes.setModel(modelo);

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error al cargar afiches: " + ex.getMessage());
        ex.printStackTrace();
    }
}


    private String quitarTildes(String texto) {
        if (texto == null) {
            return "";
        }
        texto = Normalizer.normalize(texto, Normalizer.Form.NFD);
        return texto.replaceAll("\\p{InCombiningDiacriticalMarks}+", "");
    }

    private void filtrarLista() {
        String texto = BuscadorDoctores.getText();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(TablaReportes.getModel());
        TablaReportes.setRowSorter(sorter);

        // Aplica el filtro solo a la columna "Doctor", que está en el índice 1
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto, 1));
    }



    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        String nombreDoctorFiltro = quitarTildes(NombreDoctor.getText().trim().toLowerCase());
        Date desde = FechaDesde.getDate();
        Date hasta = FechaHasta.getDate();

        if (desde == null || hasta == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar ambas fechas (desde y hasta).");
            return;
        }

        if (desde.after(hasta)) {
            JOptionPane.showMessageDialog(this, "La fecha 'Desde' no puede ser mayor que la fecha 'Hasta'.");
            return;
        }

        // Limpiar hora de las fechas para comparar solo fechas
        Calendar calDesde = Calendar.getInstance();
        calDesde.setTime(desde);
        calDesde.set(Calendar.HOUR_OF_DAY, 0);
        calDesde.set(Calendar.MINUTE, 0);
        calDesde.set(Calendar.SECOND, 0);
        calDesde.set(Calendar.MILLISECOND, 0);
        final Date desdeFinal = calDesde.getTime();

        Calendar calHasta = Calendar.getInstance();
        calHasta.setTime(hasta);
        calHasta.set(Calendar.HOUR_OF_DAY, 23);
        calHasta.set(Calendar.MINUTE, 59);
        calHasta.set(Calendar.SECOND, 59);
        calHasta.set(Calendar.MILLISECOND, 999);
        final Date hastaFinal = calHasta.getTime();

        TableRowSorter<TableModel> sorter = new TableRowSorter<>(TablaReportes.getModel());
        TablaReportes.setRowSorter(sorter);

        List<RowFilter<Object, Object>> filtros = new ArrayList<>();

        // Filtro por nombre de doctor (columna 1)
        if (!nombreDoctorFiltro.isEmpty()) {
            filtros.add(new RowFilter<>() {
                @Override
                public boolean include(Entry<? extends Object, ? extends Object> entry) {
                    String doctor = quitarTildes(entry.getStringValue(1).toLowerCase());
                    return doctor.contains(nombreDoctorFiltro);
                }
            });
        }

        // Filtro por fechas (columna 4)
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        filtros.add(new RowFilter<>() {
            @Override
            public boolean include(Entry<? extends Object, ? extends Object> entry) {
                try {
                    String fechaTexto = entry.getStringValue(4);
                    Date fecha = df.parse(fechaTexto);
                    return !fecha.before(desdeFinal) && !fecha.after(hastaFinal);
                } catch (ParseException e) {
                    return false;
                }
            }
        });

        sorter.setRowFilter(RowFilter.andFilter(filtros));
    }//GEN-LAST:event_BuscarActionPerformed
    
    private void TotalDetalladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalDetalladoActionPerformed
        TablaReportes.setRowSorter(null);
        cargaTablaReporte();
        filtrarLista(); 
    }//GEN-LAST:event_TotalDetalladoActionPerformed

    private void btnAdminCajerosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminCajerosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminCajerosMouseExited

    private void btnAdminCajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCajerosActionPerformed
        AdministradorCajeros admincaj = new AdministradorCajeros();
        admincaj.setLocationRelativeTo(null);
        admincaj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminCajerosActionPerformed

    private void btnListaLaboratoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaLaboratoriosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaLaboratoriosMouseExited

    private void btnListaLaboratoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaLaboratoriosActionPerformed
        AdministradorDoctores admindoc = new AdministradorDoctores();
        admindoc.setLocationRelativeTo(null);
        admindoc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListaLaboratoriosActionPerformed

    private void btnReportePagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportePagosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportePagosMouseExited

    private void btnReportePagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportePagosActionPerformed

    }//GEN-LAST:event_btnReportePagosActionPerformed

    private void btnServiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServiciosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServiciosMouseExited

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        ServiciosPrecios serv = new ServiciosPrecios();
        serv.setLocationRelativeTo(null);
        serv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited

    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Login cerrar = new Login();
        cerrar.setLocationRelativeTo(null);
        cerrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void BuscadorDoctoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscadorDoctoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscadorDoctoresActionPerformed

    private void btnCalcularPagoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPagoTotalActionPerformed
        String seleccion = TotalDetallado.getSelectedItem().toString();
        TableModel modelo = TablaReportes.getModel();
        double sumaTotal = 0;

        int colPrecio = -1;
        for (int i = 0; i < modelo.getColumnCount(); i++) {
            String nombreCol = modelo.getColumnName(i).toLowerCase();
            if (seleccion.equals("Total") && nombreCol.equals("servicio total")) {
                colPrecio = i;
                break;
            } else if (seleccion.equals("Detallado") && nombreCol.equals("precio del servicio")) {
                colPrecio = i;
                break;
            }
        }

        if (colPrecio == -1) {
            JOptionPane.showMessageDialog(this, "No se encontró la columna de precio correspondiente.");
            return;
        }

        for (int i = 0; i < TablaReportes.getRowCount(); i++) {
            int rowIndex = TablaReportes.convertRowIndexToModel(i);
            Object val = modelo.getValueAt(rowIndex, colPrecio);

            if (val != null) {
                try {
                    String strVal = val.toString().replace("Bs.", "").replace(",", ".").trim();
                    sumaTotal += Double.parseDouble(strVal);
                } catch (NumberFormatException e) {
                    e.printStackTrace();
                }
            }
        }

        JOptionPane.showMessageDialog(this, "Pago total: Bs. " + String.format("%.2f", sumaTotal));
        TotalPago.setText("Bs. " + String.format("%.2f", sumaTotal));
    }//GEN-LAST:event_btnCalcularPagoTotalActionPerformed

    private void ReportePagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportePagosMouseClicked
        int filaVista = TablaReportes.getSelectedRow();
        if (filaVista == -1) {
            return; // Nada seleccionado
        }
        int filaModelo = TablaReportes.convertRowIndexToModel(filaVista);

        DefaultTableModel modelo = (DefaultTableModel) TablaReportes.getModel();
        Object valorDoctor = modelo.getValueAt(filaModelo, 1); // Columna 1: Doctor

        if (valorDoctor != null) {
            NombreDoctor.setText(valorDoctor.toString());
        }
    }//GEN-LAST:event_ReportePagosMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        NombreDoctor.setText("");
        FechaDesde.setDate(null);
        FechaHasta.setDate(null);
        TablaReportes.setRowSorter(null);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void ReporteVistaPreviaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReporteVistaPreviaMouseClicked
                int filaVista = TablaReportes.getSelectedRow();
        if (filaVista == -1) {
            return; // No hay selección
        }
        int filaModelo = TablaReportes.convertRowIndexToModel(filaVista);
        DefaultTableModel modelo = (DefaultTableModel) TablaReportes.getModel();

        // Obtener doctor y mostrarlo en DoctorSeleccionado (solo vista previa)
        Object valorDoctor = modelo.getValueAt(filaModelo, 1); // Columna 1: Doctor
        if (valorDoctor != null) {
            DoctorSeleccionado.setText(valorDoctor.toString());
        }
    }//GEN-LAST:event_ReporteVistaPreviaMouseClicked

    private void NombreDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreDoctorActionPerformed

    private void TotalPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPagoActionPerformed

    /**
     * @param args the command liNombreDoctoruments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e){
            e.printStackTrace();
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportespagarMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuscadorDoctores;
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField DoctorSeleccionado;
    private com.toedter.calendar.JDateChooser FechaDesde;
    private com.toedter.calendar.JDateChooser FechaHasta;
    private javax.swing.JLabel FondoGris;
    private javax.swing.JLabel ListaPersonal1;
    private javax.swing.JTextField NombreDoctor;
    private javax.swing.JPanel Superior;
    private javax.swing.JTable TablaReportes;
    private javax.swing.JComboBox<String> TotalDetallado;
    private javax.swing.JTextField TotalPago;
    private javax.swing.JButton btnAdminCajeros;
    private javax.swing.JButton btnCalcularPagoTotal;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListaLaboratorios;
    private javax.swing.JButton btnReportePagos;
    private javax.swing.JButton btnServicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
