/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administrador;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.Date;
import ConexionLogin.Conexion;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author Rafael
 */
public class AdministradorDoctores extends javax.swing.JFrame {

    /**
     * Creates new form AdministradorDoctores
     */
    public AdministradorDoctores() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        cargarTabla();
        ID.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Superior = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ListaPersonal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMedicos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        CI = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        AgregarTecnico = new javax.swing.JLabel();
        EspecialidadLabel = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Categoria = new javax.swing.JComboBox<>();
        OtroLabel = new javax.swing.JLabel();
        Especialidad = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        FechaNacimiento = new com.toedter.calendar.JDateChooser();
        Direccion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        NombreCategoria = new javax.swing.JTextField();
        FondoGris = new javax.swing.JLabel();
        FondoBlanco = new javax.swing.JLabel();
        panelSidebar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        lblFlecha = new javax.swing.JLabel();
        btnListaLaboratorios = new javax.swing.JButton();
        btnListaPrestamos = new javax.swing.JButton();
        btnSolicitudes = new javax.swing.JButton();
        btnSancionesDesignar = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnMateriales = new javax.swing.JButton();
        btnComputadoras = new javax.swing.JButton();
        panelSubReportes = new javax.swing.JPanel();
        btnReporteLaboratorios = new javax.swing.JButton();
        btnReporteMantenimiento = new javax.swing.JButton();
        btnReporteSanciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Superior.setBackground(new java.awt.Color(80, 35, 100));
        Superior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaPersonal.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        ListaPersonal.setText("Lista de Médicos");
        jPanel2.add(ListaPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 340, -1));

        TablaMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "CI", "Teléfono", "Fecha de Nacimiento", "Dirección", "Categoria Profesional", "Especialidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMedicosMouseClicked(evt);
            }
        });
        TablaMedicos.getTableHeader().setReorderingAllowed(false);
        TablaMedicos.getTableHeader().setResizingAllowed(false);
        TablaMedicos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaMedicos.setFocusable(false);
        jScrollPane1.setViewportView(TablaMedicos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1190, 860));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));

        jTextField1.setBackground(new java.awt.Color(233, 236, 239));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setText("Buscar");
        jTextField1.setToolTipText("");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 15, 90, 20));
        String placeholder = "Buscar Nombre";

        jTextField1.setText(placeholder);
        jTextField1.setForeground(Color.GRAY);

        jTextField1.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (jTextField1.getText().equals(placeholder)) {
                    jTextField1.setText("");
                    jTextField1.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (jTextField1.getText().isEmpty()) {
                    jTextField1.setText(placeholder);
                    jTextField1.setForeground(Color.GRAY);
                }
            }
        });

        jTextField1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable();
            }

            private void filterTable() {
                String query = jTextField1.getText().toLowerCase();

                if (query.equals(placeholder.toLowerCase())) {
                    TablaMedicos.setRowSorter(null);
                    return;
                }

                TableRowSorter<TableModel> sorter = new TableRowSorter<>(TablaMedicos.getModel());
                TablaMedicos.setRowSorter(sorter);

                if (query.trim().isEmpty()) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + query, 1, 3));
                }
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_1.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 190, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1190, 910));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 194, 194)));
        jPanel1.setToolTipText("");
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Apellido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("CI:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 440, -1));

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 440, -1));

        Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 440, -1));

        CI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIActionPerformed(evt);
            }
        });
        jPanel1.add(CI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 440, -1));

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 10, -1));

        AgregarTecnico.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        AgregarTecnico.setText("Agregar Médicos");
        jPanel1.add(AgregarTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        EspecialidadLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EspecialidadLabel.setText("Especialidad:");
        jPanel1.add(EspecialidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, 20));

        guardar.setBackground(new java.awt.Color(80, 35, 100));
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, -1));

        modificar.setBackground(new java.awt.Color(80, 35, 100));
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 100, -1));

        eliminar.setBackground(new java.awt.Color(255, 0, 0));
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 100, -1));

        limpiar.setBackground(new java.awt.Color(80, 35, 100));
        limpiar.setForeground(new java.awt.Color(255, 255, 255));
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 100, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Dirección:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));

        Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Especialista", "Otro"}));
        Especialidad.setVisible(false);
        EspecialidadLabel.setVisible(false);
        OtroLabel.setVisible(false);
        NombreCategoria.setVisible(false);

        Categoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                    String seleccionado = (String) Categoria.getSelectedItem();

                    if ("General".equals(seleccionado)) {
                        Especialidad.setVisible(false);
                        EspecialidadLabel.setVisible(false);
                        OtroLabel.setVisible(false);
                        NombreCategoria.setVisible(false);
                    } else if ("Especialista".equals(seleccionado)) {
                        Especialidad.setVisible(true);
                        EspecialidadLabel.setVisible(true);
                        OtroLabel.setVisible(false);
                        NombreCategoria.setVisible(false);
                    } else if ("Otro".equals(seleccionado)) {
                        Especialidad.setVisible(false);
                        EspecialidadLabel.setVisible(false);
                        OtroLabel.setVisible(true);
                        NombreCategoria.setVisible(true);
                    }
                }
            }
        });
        jPanel1.add(Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 170, -1));

        OtroLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OtroLabel.setText("Nombre de Categoria:");
        jPanel1.add(OtroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 20));

        Especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "Cardiología",
            "Gastroenterología",
            "Neumología",
            "Neurología",
            "Oncología",
            "Pediatría",
            "Dermatología",
            "Endocrinología",
            "Hematología",
            "Infectología",
            "Reumatología",
            "Neurocirugía",
            "Cirugía Cardiovascular",
            "Cirugía Plástica",
            "Obstetricia",
            "Ginecología",
            "Urología",
            "Oftalmología",
            "Otorrinolaringología",
            "Radiología" }));
jPanel1.add(Especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 170, -1));

jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
jLabel16.setText("Teléfono:");
jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));
jPanel1.add(FechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 440, -1));
jPanel1.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 440, -1));

jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
jLabel17.setText("Fecha de Nacimiento:");
jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
jLabel18.setText("Categoría Profesional:");
jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));
jPanel1.add(NombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 440, -1));

jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 50, 660, 330));

getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1880, 980));

FondoGris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Background.jpg"))); // NOI18N
getContentPane().add(FondoGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_2.png"))); // NOI18N
getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 680, 410));

panelSidebar.setBackground(new java.awt.Color(33, 14, 68));
panelSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
jLabel15.setForeground(new java.awt.Color(102, 102, 102));
jLabel15.setText("Panel de Control");
panelSidebar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

jPanel7.setBackground(new java.awt.Color(0, 0, 0));
panelSidebar.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 30));

jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrarsesion.png"))); // NOI18N
panelSidebar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 1040, 20, 40));

btnCerrarSesion.setBackground(new java.awt.Color(33, 14, 68));
btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
btnCerrarSesion.setForeground(new java.awt.Color(241, 241, 241));
btnCerrarSesion.setText("Cerrar Sesión");
btnCerrarSesion.setBorder(null);
btnCerrarSesion.setHorizontalAlignment(SwingConstants.LEFT);
btnCerrarSesion.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
btnCerrarSesion.setIconTextGap(10);
btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseExited(java.awt.event.MouseEvent evt) {
        btnCerrarSesionMouseExited(evt);
    }
    });
    btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCerrarSesionActionPerformed(evt);
        }
    });
    panelSidebar.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1040, 229, 40));

    btnInicio.setBackground(new java.awt.Color(33, 14, 68));
    btnInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnInicio.setForeground(new java.awt.Color(241, 241, 241));
    btnInicio.setText("Inicio");
    btnInicio.setBorder(null);
    btnInicio.setHorizontalAlignment(SwingConstants.LEFT);
    btnInicio.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
    btnInicio.setIconTextGap(10);
    btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnInicioMouseExited(evt);
        }
    });
    btnInicio.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnInicioActionPerformed(evt);
        }
    });
    panelSidebar.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 229, 40));

    lblFlecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MostrarMasBoton.png"))); // NOI18N
    panelSidebar.add(lblFlecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 382, 20, 20));

    btnListaLaboratorios.setBackground(new java.awt.Color(33, 14, 68));
    btnListaLaboratorios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnListaLaboratorios.setForeground(new java.awt.Color(241, 241, 241));
    btnListaLaboratorios.setText("Laboratorios");
    btnListaLaboratorios.setBorder(null);
    btnListaLaboratorios.setHorizontalAlignment(SwingConstants.LEFT);
    btnListaLaboratorios.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
    btnListaLaboratorios.setIconTextGap(10);
    btnListaLaboratorios.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnListaLaboratoriosMouseExited(evt);
        }
    });
    btnListaLaboratorios.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnListaLaboratoriosActionPerformed(evt);
        }
    });
    panelSidebar.add(btnListaLaboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 229, 40));

    btnListaPrestamos.setBackground(new java.awt.Color(33, 14, 68));
    btnListaPrestamos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnListaPrestamos.setForeground(new java.awt.Color(241, 241, 241));
    btnListaPrestamos.setText("Prestamos");
    btnListaPrestamos.setBorder(null);
    btnListaPrestamos.setHorizontalAlignment(SwingConstants.LEFT);
    btnListaPrestamos.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
    btnListaPrestamos.setIconTextGap(10);
    btnListaPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnListaPrestamosMouseExited(evt);
        }
    });
    btnListaPrestamos.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnListaPrestamosActionPerformed(evt);
        }
    });
    panelSidebar.add(btnListaPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 229, 40));

    btnSolicitudes.setBackground(new java.awt.Color(33, 14, 68));
    btnSolicitudes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnSolicitudes.setForeground(new java.awt.Color(241, 241, 241));
    btnSolicitudes.setText("Solicitudes");
    btnSolicitudes.setBorder(null);
    btnSolicitudes.setHorizontalAlignment(SwingConstants.LEFT);
    btnSolicitudes.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
    btnSolicitudes.setIconTextGap(10);
    btnSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnSolicitudesMouseExited(evt);
        }
    });
    btnSolicitudes.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSolicitudesActionPerformed(evt);
        }
    });
    panelSidebar.add(btnSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 229, 40));

    btnSancionesDesignar.setBackground(new java.awt.Color(33, 14, 68));
    btnSancionesDesignar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnSancionesDesignar.setForeground(new java.awt.Color(241, 241, 241));
    btnSancionesDesignar.setText("Sanciones");
    btnSancionesDesignar.setBorder(null);
    btnSancionesDesignar.setHorizontalAlignment(SwingConstants.LEFT);
    btnSancionesDesignar.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
    btnSancionesDesignar.setIconTextGap(10);
    btnSancionesDesignar.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnSancionesDesignarMouseExited(evt);
        }
    });
    btnSancionesDesignar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSancionesDesignarActionPerformed(evt);
        }
    });
    panelSidebar.add(btnSancionesDesignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 229, 40));

    btnReportes.setBackground(new java.awt.Color(33, 14, 68));
    btnReportes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnReportes.setForeground(new java.awt.Color(241, 241, 241));
    btnReportes.setText("Reportes");
    btnReportes.setBorder(null);
    btnReportes.setHorizontalAlignment(SwingConstants.LEFT);
    btnReportes.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
    btnReportes.setIconTextGap(10);
    btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnReportesMouseExited(evt);
        }
    });
    btnReportes.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnReportesActionPerformed(evt);
        }
    });
    panelSidebar.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 229, 40));

    btnMateriales.setBackground(new java.awt.Color(33, 14, 68));
    btnMateriales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnMateriales.setForeground(new java.awt.Color(241, 241, 241));
    btnMateriales.setText("Materiales");
    btnMateriales.setBorder(null);
    btnMateriales.setHorizontalAlignment(SwingConstants.LEFT);
    btnMateriales.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
    btnMateriales.setIconTextGap(10);
    btnMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnMaterialesMouseExited(evt);
        }
    });
    btnMateriales.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnMaterialesActionPerformed(evt);
        }
    });
    panelSidebar.add(btnMateriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 229, 40));

    btnComputadoras.setBackground(new java.awt.Color(33, 14, 68));
    btnComputadoras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnComputadoras.setForeground(new java.awt.Color(241, 241, 241));
    btnComputadoras.setText("Computadoras");
    btnComputadoras.setBorder(null);
    btnComputadoras.setHorizontalAlignment(SwingConstants.LEFT);
    btnComputadoras.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
    btnComputadoras.setIconTextGap(10);
    btnComputadoras.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnComputadorasMouseExited(evt);
        }
    });
    btnComputadoras.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnComputadorasActionPerformed(evt);
        }
    });
    panelSidebar.add(btnComputadoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 229, 40));

    panelSubReportes.setBackground(new java.awt.Color(16, 23, 32));
    panelSubReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btnReporteLaboratorios.setBackground(new java.awt.Color(16, 23, 32));
    btnReporteLaboratorios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnReporteLaboratorios.setForeground(new java.awt.Color(241, 241, 241));
    btnReporteLaboratorios.setText("Prestamos");
    btnReporteLaboratorios.setBorder(null);
    btnReporteLaboratorios.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnReporteLaboratoriosMouseExited(evt);
        }
    });
    btnReporteLaboratorios.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnReporteLaboratoriosActionPerformed(evt);
        }
    });
    panelSubReportes.add(btnReporteLaboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 40));

    btnReporteMantenimiento.setBackground(new java.awt.Color(16, 23, 32));
    btnReporteMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnReporteMantenimiento.setForeground(new java.awt.Color(241, 241, 241));
    btnReporteMantenimiento.setText("Mantenimiento");
    btnReporteMantenimiento.setBorder(null);
    btnReporteMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnReporteMantenimientoMouseExited(evt);
        }
    });
    btnReporteMantenimiento.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnReporteMantenimientoActionPerformed(evt);
        }
    });
    panelSubReportes.add(btnReporteMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 230, 40));

    btnReporteSanciones.setBackground(new java.awt.Color(16, 23, 32));
    btnReporteSanciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnReporteSanciones.setForeground(new java.awt.Color(255, 255, 255));
    btnReporteSanciones.setText("Sanciones");
    btnReporteSanciones.setBorder(null);
    btnReporteSanciones.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnReporteSancionesActionPerformed(evt);
        }
    });
    panelSubReportes.add(btnReporteSanciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 230, 40));

    panelSidebar.add(panelSubReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 230, 330));

    getContentPane().add(panelSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1080));

    pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{
            "ID", "CI", "Nombre", "Apellido", "Fecha Nacimiento", "Teléfono", "Dirección", "Categoría Profesional", "Especialidad"
        });

        try {
            Connection con = Conexion.obtenerConexion();
            PreparedStatement ps = con.prepareStatement(
                    "SELECT id_medico, CI, nombre, apellido, fecha_nacimiento, telefono, direccion, categoria_profesional, categoria_profesional_otro, especialidad FROM medicos WHERE estado = 1 "
            );
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                String categoria = rs.getString("categoria_profesional");
                String otro = rs.getString("categoria_profesional_otro");

                String categoriaMostrar;
                if ("Otro".equalsIgnoreCase(categoria)) {
                    categoriaMostrar = (otro != null && !otro.trim().isEmpty()) ? otro : "Otro";
                } else {
                    categoriaMostrar = categoria;
                }

                modelo.addRow(new Object[]{
                    rs.getInt("id_medico"),
                    rs.getString("CI"),
                    rs.getString("nombre"),
                    rs.getString("apellido"),
                    rs.getDate("fecha_nacimiento"),
                    rs.getString("telefono"),
                    rs.getString("direccion"),
                    categoriaMostrar,
                    rs.getString("especialidad")
                });
            }

            TablaMedicos.setModel(modelo);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar los médicos: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoActionPerformed

    private void CIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CIActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        ID.setVisible(false);
    }//GEN-LAST:event_IDActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        String nombretxt = Nombre.getText().trim();
        String apellidotxt = Apellido.getText().trim();
        String citxt = CI.getText().trim();
        String telefonotxt = Telefono.getText().trim();
        Date fechanacimientotxt = FechaNacimiento.getDate();
        String direcciontxt = Direccion.getText().trim();
        String categoriatxt = Categoria.getSelectedItem().toString(); 
        String especialidadtxt = null;
        String categoriaProfesionalOtro = null;

        if (nombretxt.isEmpty() || apellidotxt.isEmpty() || citxt.isEmpty()
                || fechanacimientotxt == null || categoriatxt.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, rellene todos los campos obligatorios.");
            return;
        }

        if (categoriatxt.equals("Especialista")) {
            if (Especialidad.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(null, "Por favor, seleccione una especialidad.");
                return;
            }
            especialidadtxt = Especialidad.getSelectedItem().toString().trim();
            if (especialidadtxt.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, seleccione una especialidad.");
                return;
            }
        }

        if (categoriatxt.equals("Otro")) {
            categoriaProfesionalOtro = NombreCategoria.getText().trim();
            if (categoriaProfesionalOtro.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese la categoría profesional.");
                return;
            }
        }

        try {
            Integer.parseInt(citxt);
            if (!telefonotxt.isEmpty()) {
                Integer.parseInt(telefonotxt);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "CI y Teléfono deben ser números válidos.");
            return;
        }

        try {
            Connection con = Conexion.obtenerConexion();

            PreparedStatement psMedico = con.prepareStatement(
                    "INSERT INTO medicos(CI, nombre, apellido, fecha_nacimiento, telefono, direccion, categoria_profesional, categoria_profesional_otro, especialidad, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 1)");
            psMedico.setString(1, citxt);
            psMedico.setString(2, nombretxt);
            psMedico.setString(3, apellidotxt);
            psMedico.setDate(4, new java.sql.Date(fechanacimientotxt.getTime()));

            
            if (!telefonotxt.isEmpty()) {
                psMedico.setString(5, telefonotxt);
            } else {
                psMedico.setNull(5, java.sql.Types.VARCHAR);
            }

            
            if (!direcciontxt.isEmpty()) {
                psMedico.setString(6, direcciontxt);
            } else {
                psMedico.setNull(6, java.sql.Types.VARCHAR);
            }

            psMedico.setString(7, categoriatxt);

            if (categoriatxt.equals("Otro")) {
                psMedico.setString(8, categoriaProfesionalOtro);
            } else {
                psMedico.setNull(8, java.sql.Types.VARCHAR);
            }

            if (categoriatxt.equals("Especialista")) {
                psMedico.setString(9, especialidadtxt);
            } else {
                psMedico.setNull(9, java.sql.Types.VARCHAR);
            }

            psMedico.executeUpdate();

            JOptionPane.showMessageDialog(null, "Registro guardado correctamente.");

            limpiar();
            cargarTabla();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la base de datos: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        String nombretxt = Nombre.getText().trim();
        String apellidotxt = Apellido.getText().trim();
        String citxt = CI.getText().trim();
        String telefonotxt = Telefono.getText().trim();
        Date fechanacimientotxt = FechaNacimiento.getDate();
        String direcciontxt = Direccion.getText().trim();
        String categoriatxt = Categoria.getSelectedItem().toString();
        String especialidadtxt = null;
        String categoriaProfesionalOtro = null;

        if (nombretxt.isEmpty() || apellidotxt.isEmpty() || citxt.isEmpty()
                || fechanacimientotxt == null || categoriatxt.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, rellene todos los campos obligatorios.");
            return;
        }

        if (categoriatxt.equals("Especialista")) {
            if (Especialidad.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(null, "Por favor, seleccione una especialidad.");
                return;
            }
            especialidadtxt = Especialidad.getSelectedItem().toString().trim();
            if (especialidadtxt.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, seleccione una especialidad.");
                return;
            }
        }

        if (categoriatxt.equals("Otro")) {
            categoriaProfesionalOtro = NombreCategoria.getText().trim();
            if (categoriaProfesionalOtro.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese la categoría profesional.");
                return;
            }
        }

        try {
            Integer.parseInt(citxt);
            if (!telefonotxt.isEmpty()) {
                Integer.parseInt(telefonotxt);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "CI y Teléfono deben ser números válidos.");
            return;
        }

        try {
            Connection con = Conexion.obtenerConexion();

            PreparedStatement psMedico = con.prepareStatement(
                    "UPDATE medicos SET nombre=?, apellido=?, fecha_nacimiento=?, telefono=?, direccion=?, categoria_profesional=?, categoria_profesional_otro=?, especialidad=? WHERE CI=?");

            psMedico.setString(1, nombretxt);
            psMedico.setString(2, apellidotxt);
            psMedico.setDate(3, new java.sql.Date(fechanacimientotxt.getTime()));

            
            if (!telefonotxt.isEmpty()) {
                psMedico.setString(4, telefonotxt);
            } else {
                psMedico.setNull(4, java.sql.Types.VARCHAR);
            }

            
            if (!direcciontxt.isEmpty()) {
                psMedico.setString(5, direcciontxt);
            } else {
                psMedico.setNull(5, java.sql.Types.VARCHAR);
            }

            psMedico.setString(6, categoriatxt);

            if (categoriatxt.equals("Otro")) {
                psMedico.setString(7, categoriaProfesionalOtro);
            } else {
                psMedico.setNull(7, java.sql.Types.VARCHAR);
            }

            if (categoriatxt.equals("Especialista")) {
                psMedico.setString(8, especialidadtxt);
            } else {
                psMedico.setNull(8, java.sql.Types.VARCHAR);
            }

            psMedico.setString(9, citxt); 

            int filasAfectadas = psMedico.executeUpdate();

            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(null, "Registro modificado correctamente.");
                limpiar();
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el médico con la CI especificada.");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la base de datos: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        int fila = TablaMedicos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un médico para eliminar");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
                null,
                "¿Está seguro de que desea eliminar este registro?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        int medicoId = Integer.parseInt(ID.getText());

        try {
            Connection con = Conexion.obtenerConexion();

            PreparedStatement psVerificar = con.prepareStatement(
                    "SELECT estado, id_usuario FROM medicos WHERE id_medico = ?"
            );
            psVerificar.setInt(1, medicoId);
            ResultSet rs = psVerificar.executeQuery();

            if (rs.next()) {
                int estado = rs.getInt("estado");
                int idUsuario = rs.getInt("id_usuario");

                if (estado == 0) {
                    JOptionPane.showMessageDialog(null, "El médico ya fue eliminado anteriormente");
                    return;
                }

                PreparedStatement psActualizarEstado = con.prepareStatement(
                        "UPDATE medicos SET estado = 0 WHERE id_medico = ?"
                );
                psActualizarEstado.setInt(1, medicoId);
                psActualizarEstado.executeUpdate();


                JOptionPane.showMessageDialog(null, "Registro marcado como eliminado");
                limpiar();
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró al médico seleccionado");
            }
        } catch (SQLException ex) {
            System.out.println("Error en eliminación lógica: " + ex.toString());
            JOptionPane.showMessageDialog(null, "Error en la eliminación lógica: " + ex.getMessage());
        }
    }//GEN-LAST:event_eliminarActionPerformed
    private void limpiar() {
        CI.setText("");
        Nombre.setText("");
        Apellido.setText("");
        FechaNacimiento.setDate(null);
        Telefono.setText("");
        Direccion.setText("");
        Categoria.setSelectedIndex(0); 
        Especialidad.setSelectedIndex(0); 
    }

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_limpiarActionPerformed

    private void TablaMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMedicosMouseClicked
        try {
            int fila = TablaMedicos.getSelectedRow();
            if (fila == -1) {
                return;
            }

            int id = Integer.parseInt(TablaMedicos.getValueAt(fila, 0).toString());

            Connection con = Conexion.obtenerConexion();
            PreparedStatement ps = con.prepareStatement(
                    "SELECT CI, nombre, apellido, fecha_nacimiento, telefono, direccion, categoria_profesional, categoria_profesional_otro, especialidad FROM medicos WHERE id_medico = ?"
            );
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                ID.setText(String.valueOf(id));
                CI.setText(rs.getString("CI"));
                Nombre.setText(rs.getString("nombre"));
                Apellido.setText(rs.getString("apellido"));

                java.sql.Date fecha = rs.getDate("fecha_nacimiento");
                if (fecha != null) {
                    FechaNacimiento.setDate(new java.util.Date(fecha.getTime()));
                } else {
                    FechaNacimiento.setDate(null);
                }

                Telefono.setText(rs.getString("telefono"));
                Direccion.setText(rs.getString("direccion"));

                String categoria = rs.getString("categoria_profesional");
                String especialidad = rs.getString("especialidad");
                String otroCategoria = rs.getString("categoria_profesional_otro");

                if (categoria.equalsIgnoreCase("General")) {
                    Categoria.setSelectedItem("General");
                    Especialidad.setVisible(false);
                    EspecialidadLabel.setVisible(false);
                    NombreCategoria.setVisible(false);
                    OtroLabel.setVisible(false);
                } else if (categoria.equalsIgnoreCase("Especialista")) {
                    Categoria.setSelectedItem("Especialista");
                    Especialidad.setVisible(true);
                    EspecialidadLabel.setVisible(true);
                    NombreCategoria.setVisible(false);
                    OtroLabel.setVisible(false);

                    if (especialidad != null) {
                        Especialidad.setSelectedItem(especialidad);
                    }
                } else {
                    Categoria.setSelectedItem("Otro");
                    NombreCategoria.setVisible(true);
                    OtroLabel.setVisible(true);
                    NombreCategoria.setText(otroCategoria != null ? otroCategoria : "");
                    Especialidad.setVisible(false);
                    EspecialidadLabel.setVisible(false);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_TablaMedicosMouseClicked

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited

    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed

    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed

    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnListaLaboratoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaLaboratoriosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaLaboratoriosMouseExited

    private void btnListaLaboratoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaLaboratoriosActionPerformed

    }//GEN-LAST:event_btnListaLaboratoriosActionPerformed

    private void btnListaPrestamosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaPrestamosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaPrestamosMouseExited

    private void btnListaPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaPrestamosActionPerformed

    }//GEN-LAST:event_btnListaPrestamosActionPerformed

    private void btnSolicitudesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitudesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolicitudesMouseExited

    private void btnSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudesActionPerformed

    }//GEN-LAST:event_btnSolicitudesActionPerformed

    private void btnSancionesDesignarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSancionesDesignarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSancionesDesignarMouseExited

    private void btnSancionesDesignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSancionesDesignarActionPerformed

    }//GEN-LAST:event_btnSancionesDesignarActionPerformed

    private void btnReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesMouseExited

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed

    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnMaterialesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaterialesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaterialesMouseExited

    private void btnMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialesActionPerformed

    }//GEN-LAST:event_btnMaterialesActionPerformed

    private void btnComputadorasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComputadorasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComputadorasMouseExited

    private void btnComputadorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputadorasActionPerformed

    }//GEN-LAST:event_btnComputadorasActionPerformed

    private void btnReporteLaboratoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteLaboratoriosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteLaboratoriosMouseExited

    private void btnReporteLaboratoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteLaboratoriosActionPerformed

    }//GEN-LAST:event_btnReporteLaboratoriosActionPerformed

    private void btnReporteMantenimientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMantenimientoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteMantenimientoMouseExited

    private void btnReporteMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteMantenimientoActionPerformed

    }//GEN-LAST:event_btnReporteMantenimientoActionPerformed

    private void btnReporteSancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteSancionesActionPerformed

    }//GEN-LAST:event_btnReporteSancionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e){
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorDoctores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarTecnico;
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField CI;
    private javax.swing.JComboBox<String> Categoria;
    private javax.swing.JTextField Direccion;
    private javax.swing.JComboBox<String> Especialidad;
    private javax.swing.JLabel EspecialidadLabel;
    private com.toedter.calendar.JDateChooser FechaNacimiento;
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel FondoGris;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel ListaPersonal;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField NombreCategoria;
    private javax.swing.JLabel OtroLabel;
    private javax.swing.JPanel Superior;
    private javax.swing.JTable TablaMedicos;
    private javax.swing.JTextField Telefono;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnComputadoras;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnListaLaboratorios;
    private javax.swing.JButton btnListaPrestamos;
    private javax.swing.JButton btnMateriales;
    private javax.swing.JButton btnReporteLaboratorios;
    private javax.swing.JButton btnReporteMantenimiento;
    private javax.swing.JButton btnReporteSanciones;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSancionesDesignar;
    private javax.swing.JButton btnSolicitudes;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblFlecha;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton modificar;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JPanel panelSubReportes;
    // End of variables declaration//GEN-END:variables
}
