/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administrador;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.Date;
import ConexionLogin.Conexion;
import ConexionLogin.Login;
import ReportesPagos.ReportesGeneral;
import ReportesPagos.ReportespagarMedico;
import Servicios.ServiciosPrecios;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.text.Normalizer;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author Rafael
 */
public class AdministradorDoctores extends javax.swing.JFrame {

    /**
     * Creates new form AdministradorDoctores
     */
    public AdministradorDoctores() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        cargarTabla();
        cargarDatosCategoriaOtros();
        aplicarColorFilasAlternadas(TablaMedicos);
        ID.setVisible(false);
        ID.setEnabled(false);
        ID.setFocusable(false);
        ID.setRequestFocusEnabled(false);
        this.setLocationRelativeTo(null);
    }
    private void aplicarColorFilasAlternadas(JTable tabla) {
        TableCellRenderer renderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                if (isSelected) {
                    setBackground(table.getSelectionBackground());
                    setForeground(table.getSelectionForeground());
                } else {
                    if (row % 2 == 0) {
                        setBackground(Color.WHITE);
                        setForeground(Color.BLACK);
                    } else {
                        setBackground(new Color(240, 240, 240));
                        setForeground(Color.BLACK);
                    }
                }

                return this;
            }
        };

        for (int i = 0; i < tabla.getColumnCount(); i++) {
            tabla.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Superior = new javax.swing.JPanel();
        btnAdminCajeros = new javax.swing.JButton();
        btnAdminDoc = new javax.swing.JButton();
        btnReportePagos = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnReporteEspeci = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ListaPersonal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMedicos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        CI = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        AgregarTecnico = new javax.swing.JLabel();
        EspecialidadLabel = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Categoria = new javax.swing.JComboBox<>();
        OtroLabel = new javax.swing.JLabel();
        Especialidad = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        FechaNacimiento = new com.toedter.calendar.JDateChooser();
        Direccion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        NombreCategoria = new javax.swing.JTextField();
        ComboCategoriaOtros = new javax.swing.JComboBox<>();
        FondoGris = new javax.swing.JLabel();
        FondoBlanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Superior.setBackground(new java.awt.Color(0, 102, 255));
        Superior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdminCajeros.setBackground(new java.awt.Color(7, 70, 215));
        btnAdminCajeros.setForeground(new java.awt.Color(241, 241, 241));
        btnAdminCajeros.setText("Administracion de Cajeros");
        btnAdminCajeros.setBorder(null);
        btnAdminCajeros.setHorizontalAlignment(SwingConstants.LEFT);
        btnAdminCajeros.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnAdminCajeros.setIconTextGap(10);
        btnAdminCajeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdminCajerosMouseExited(evt);
            }
        });
        btnAdminCajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminCajerosActionPerformed(evt);
            }
        });
        Superior.add(btnAdminCajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        btnAdminDoc.setBackground(new java.awt.Color(7, 70, 215));
        btnAdminDoc.setForeground(new java.awt.Color(241, 241, 241));
        btnAdminDoc.setText("Administracion de Doctores");
        btnAdminDoc.setBorder(null);
        btnAdminDoc.setHorizontalAlignment(SwingConstants.LEFT);
        btnAdminDoc.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnAdminDoc.setIconTextGap(10);
        btnAdminDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdminDocMouseExited(evt);
            }
        });
        btnAdminDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminDocActionPerformed(evt);
            }
        });
        Superior.add(btnAdminDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 190, 40));

        btnReportePagos.setBackground(new java.awt.Color(7, 70, 215));
        btnReportePagos.setForeground(new java.awt.Color(241, 241, 241));
        btnReportePagos.setText("Reportes de Pagos");
        btnReportePagos.setBorder(null);
        btnReportePagos.setHorizontalAlignment(SwingConstants.LEFT);
        btnReportePagos.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnReportePagos.setIconTextGap(10);
        btnReportePagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportePagosMouseExited(evt);
            }
        });
        btnReportePagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportePagosActionPerformed(evt);
            }
        });
        Superior.add(btnReportePagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 190, 40));

        btnServicios.setBackground(new java.awt.Color(7, 70, 215));
        btnServicios.setForeground(new java.awt.Color(241, 241, 241));
        btnServicios.setText("Servicios");
        btnServicios.setBorder(null);
        btnServicios.setHorizontalAlignment(SwingConstants.LEFT);
        btnServicios.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnServicios.setIconTextGap(10);
        btnServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnServiciosMouseExited(evt);
            }
        });
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        Superior.add(btnServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 190, 40));

        btnReporteEspeci.setBackground(new java.awt.Color(7, 70, 215));
        btnReporteEspeci.setForeground(new java.awt.Color(241, 241, 241));
        btnReporteEspeci.setText("Reportes");
        btnReporteEspeci.setBorder(null);
        btnReporteEspeci.setHorizontalAlignment(SwingConstants.LEFT);
        btnReporteEspeci.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnReporteEspeci.setIconTextGap(10);
        btnReporteEspeci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteEspeciMouseExited(evt);
            }
        });
        btnReporteEspeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteEspeciActionPerformed(evt);
            }
        });
        Superior.add(btnReporteEspeci, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrarsesion.png"))); // NOI18N
        Superior.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, 20, 20));

        btnCerrarSesion.setBackground(new java.awt.Color(7, 70, 215));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setHorizontalAlignment(SwingConstants.LEFT);
        btnCerrarSesion.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnCerrarSesion.setIconTextGap(10);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        Superior.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 170, 40));

        getContentPane().add(Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaPersonal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ListaPersonal.setText("Lista de Médicos");
        jPanel2.add(ListaPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(233, 236, 239));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTextField1.setText("Buscar Médico");
        jTextField1.setToolTipText("");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 140, 20));
        String placeholder = "Buscar Médico";

        jTextField1.setText(placeholder);
        jTextField1.setForeground(Color.GRAY);

        jTextField1.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (jTextField1.getText().equals(placeholder)) {
                    jTextField1.setText("");
                    jTextField1.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (jTextField1.getText().isEmpty()) {
                    jTextField1.setText(placeholder);
                    jTextField1.setForeground(Color.GRAY);
                }
            }
        });

        jTextField1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable();
            }

            private void filterTable() {
                String query = normalize(jTextField1.getText().trim());

                if (query.equals(normalize(placeholder)) || query.isEmpty()) {
                    TablaMedicos.setRowSorter(null);
                    return;
                }

                TableRowSorter<TableModel> sorter = new TableRowSorter<>(TablaMedicos.getModel());
                TablaMedicos.setRowSorter(sorter);

                sorter.setRowFilter(new RowFilter<TableModel, Integer>() {
                    @Override
                    public boolean include(Entry<? extends TableModel, ? extends Integer> entry) {
                        String nombre = normalize(entry.getStringValue(2));
                        String apellido = normalize(entry.getStringValue(3));
                        String combinado = nombre + " " + apellido;
                        return combinado.contains(query);
                    }
                });
            }

            private String normalize(String text) {
                if (text == null) return "";
                String normalized = Normalizer.normalize(text, Normalizer.Form.NFD);
                normalized = normalized.replaceAll("\\p{InCombiningDiacriticalMarks}+", "");
                return normalized.toLowerCase();
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_1.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 190, 30));

        TablaMedicos.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TablaMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "CI", "Teléfono", "Fecha de Nacimiento", "Dirección", "Categoria Profesional", "Especialidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMedicosMouseClicked(evt);
            }
        });
        TablaMedicos.getTableHeader().setReorderingAllowed(false);
        TablaMedicos.getTableHeader().setResizingAllowed(false);
        TablaMedicos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaMedicos.setFocusable(false);
        jScrollPane1.setViewportView(TablaMedicos);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 870, 610));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 870, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 194, 194)));
        jPanel1.setToolTipText("");
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        jLabel5.setText("Apellido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        jLabel6.setText("CI:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 300, -1));

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 300, -1));

        Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 300, -1));

        CI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIActionPerformed(evt);
            }
        });
        jPanel1.add(CI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 300, -1));

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 10, 10));

        AgregarTecnico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AgregarTecnico.setText("Agregar Médicos");
        jPanel1.add(AgregarTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        EspecialidadLabel.setText("Especialidad:");
        jPanel1.add(EspecialidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, 20));

        guardar.setBackground(new java.awt.Color(7, 70, 215));
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 30));

        modificar.setBackground(new java.awt.Color(7, 70, 215));
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 100, 30));

        eliminar.setBackground(new java.awt.Color(255, 0, 0));
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 100, 30));

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 100, 30));

        jLabel14.setText("Dirección:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Especialista", "Otro"}));
        Especialidad.setVisible(false);
        EspecialidadLabel.setVisible(false);
        OtroLabel.setVisible(false);
        NombreCategoria.setVisible(false);
        ComboCategoriaOtros.setVisible(false);

        Categoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                    String seleccionado = (String) Categoria.getSelectedItem();

                    if ("General".equals(seleccionado)) {
                        Especialidad.setVisible(false);
                        EspecialidadLabel.setVisible(false);
                        OtroLabel.setVisible(false);
                        NombreCategoria.setVisible(false);
                        ComboCategoriaOtros.setVisible(false);
                    } else if ("Especialista".equals(seleccionado)) {
                        Especialidad.setVisible(true);
                        EspecialidadLabel.setVisible(true);
                        OtroLabel.setVisible(false);
                        NombreCategoria.setVisible(false);
                        ComboCategoriaOtros.setVisible(false);
                    } else if ("Otro".equals(seleccionado)) {
                        Especialidad.setVisible(false);
                        EspecialidadLabel.setVisible(false);
                        OtroLabel.setVisible(true);
                        NombreCategoria.setVisible(true);
                        ComboCategoriaOtros.setVisible(true);
                    }
                }
            }
        });
        jPanel1.add(Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 110, -1));

        OtroLabel.setText("Nombre de Categoria:");
        jPanel1.add(OtroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 20));

        Especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "Cardiología",
            "Gastroenterología",
            "Neumología",
            "Neurología",
            "Oncología",
            "Pediatría",
            "Dermatología",
            "Endocrinología",
            "Hematología",
            "Infectología",
            "Reumatología",
            "Neurocirugía",
            "Cirugía Cardiovascular",
            "Cirugía Plástica",
            "Obstetricia",
            "Ginecología",
            "Urología",
            "Oftalmología",
            "Otorrinolaringología",
            "Radiología" }));
jPanel1.add(Especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 110, -1));

jLabel16.setText("Teléfono:");
jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));
jPanel1.add(FechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 300, -1));
jPanel1.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 300, -1));

jLabel17.setText("Fecha de Nacimiento:");
jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

jLabel18.setText("Categoría Profesional:");
jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));
jPanel1.add(NombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 130, -1));

ComboCategoriaOtros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
jPanel1.add(ComboCategoriaOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 160, -1));
cargarDatosCategoriaOtros();

jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 40, 460, 330));

getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1350, 710));

FondoGris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Background.jpg"))); // NOI18N
getContentPane().add(FondoGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_2.png"))); // NOI18N
getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 680, 410));

pack();
}// </editor-fold>//GEN-END:initComponents
    private void cargarTabla() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        modelo.setColumnIdentifiers(new Object[]{
            "ID", "CI", "Nombre", "Apellido", "Fecha Nacimiento", "Teléfono", "Dirección", "Categoría Profesional", "Especialidad"
        });

        try {
            Connection con = Conexion.obtenerConexion();
            PreparedStatement ps = con.prepareStatement(
                    "SELECT id_medico, CI, nombre, apellido, fecha_nacimiento, telefono, direccion, categoria_profesional, categoria_profesional_otro, especialidad FROM medicos WHERE estado = 1 "
            );
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                String categoria = rs.getString("categoria_profesional");
                String otro = rs.getString("categoria_profesional_otro");

                String categoriaMostrar;
                if ("Otro".equalsIgnoreCase(categoria)) {
                    categoriaMostrar = (otro != null && !otro.trim().isEmpty()) ? otro : "Otro";
                } else {
                    categoriaMostrar = categoria;
                }

                modelo.addRow(new Object[]{
                    rs.getInt("id_medico"),
                    rs.getString("CI"),
                    rs.getString("nombre"),
                    rs.getString("apellido"),
                    rs.getDate("fecha_nacimiento"),
                    rs.getString("telefono"),
                    rs.getString("direccion"),
                    categoriaMostrar,
                    rs.getString("especialidad")
                });
            }

            TablaMedicos.setModel(modelo);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar los médicos: " + ex.getMessage());
            ex.printStackTrace();
        }
    }
private void cargarDatosCategoriaOtros() {
    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

    String query = "SELECT DISTINCT categoria_profesional_otro FROM medicos "
                 + "WHERE categoria_profesional_otro IS NOT NULL AND categoria_profesional_otro <> ''";

    try (
         Connection con = Conexion.obtenerConexion();
         PreparedStatement ps = con.prepareStatement(query);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            String categoriaOtro = rs.getString("categoria_profesional_otro");
            model.addElement(categoriaOtro);
        }

        ComboCategoriaOtros.setModel(model);

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error al cargar categorías: " + ex.getMessage());
        ex.printStackTrace();
    }
}


    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoActionPerformed

    private void CIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CIActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        ID.setVisible(false);
        ID.setEnabled(false);
        ID.setFocusable(false);
        ID.setRequestFocusEnabled(false);
    }//GEN-LAST:event_IDActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        String nombretxt = Nombre.getText().trim();
        String apellidotxt = Apellido.getText().trim();
        String citxt = CI.getText().trim();
        String telefonotxt = Telefono.getText().trim();
        Date fechanacimientotxt = FechaNacimiento.getDate();
        String direcciontxt = Direccion.getText().trim();
        String categoriatxt = Categoria.getSelectedItem().toString();
        String especialidadtxt = null;
        String categoriaProfesionalOtro = null;

        if (nombretxt.isEmpty() || apellidotxt.isEmpty() || categoriatxt.isEmpty() || citxt.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, rellene los campos obligatorios: Nombre, Apellido, Categoría y CI.");
            return;
        }

        try {
            Integer.parseInt(citxt);
            if (!telefonotxt.isEmpty()) {
                Integer.parseInt(telefonotxt);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "CI y Teléfono deben ser números válidos.");
            return;
        }

        if (categoriatxt.equals("General")) {
            especialidadtxt = "Medicina General";
        } else if (categoriatxt.equals("Especialista")) {
            if (Especialidad.getSelectedItem() == null || Especialidad.getSelectedItem().toString().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, seleccione una especialidad.");
                return;
            }
            especialidadtxt = Especialidad.getSelectedItem().toString().trim();
        } else if (categoriatxt.equals("Otro")) {
            String nombreCat = NombreCategoria.getText().trim();
            Object seleccionadoCombo = ComboCategoriaOtros.getSelectedItem();

            if (!nombreCat.isEmpty()) {
                categoriaProfesionalOtro = nombreCat;
            } else if (seleccionadoCombo != null && !seleccionadoCombo.toString().trim().isEmpty()) {
                categoriaProfesionalOtro = seleccionadoCombo.toString().trim();
            } else {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese o seleccione una categoría profesional válida.");
                return;
            }
        }

        try {
            Connection con = Conexion.obtenerConexion();

            PreparedStatement verificarCI = con.prepareStatement("SELECT COUNT(*) FROM medicos WHERE CI = ?");
            verificarCI.setString(1, citxt);
            ResultSet rs = verificarCI.executeQuery();
            if (rs.next() && rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(null, "Ya existe un médico registrado con el mismo CI.");
                rs.close();
                verificarCI.close();
                return;
            }
            rs.close();
            verificarCI.close();

            PreparedStatement psMedico = con.prepareStatement(
                    "INSERT INTO medicos(CI, nombre, apellido, fecha_nacimiento, telefono, direccion, categoria_profesional, categoria_profesional_otro, especialidad, estado) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 1)"
            );

            psMedico.setString(1, citxt);
            psMedico.setString(2, nombretxt);
            psMedico.setString(3, apellidotxt);

            if (fechanacimientotxt != null) {
                psMedico.setDate(4, new java.sql.Date(fechanacimientotxt.getTime()));
            } else {
                psMedico.setNull(4, java.sql.Types.DATE);
            }

            if (!telefonotxt.isEmpty()) {
                psMedico.setString(5, telefonotxt);
            } else {
                psMedico.setNull(5, java.sql.Types.VARCHAR);
            }

            if (!direcciontxt.isEmpty()) {
                psMedico.setString(6, direcciontxt);
            } else {
                psMedico.setNull(6, java.sql.Types.VARCHAR);
            }

            psMedico.setString(7, categoriatxt);

            if (categoriatxt.equals("Otro")) {
                psMedico.setString(8, categoriaProfesionalOtro);
            } else {
                psMedico.setNull(8, java.sql.Types.VARCHAR);
            }

            if (especialidadtxt != null) {
                psMedico.setString(9, especialidadtxt);
            } else {
                psMedico.setNull(9, java.sql.Types.VARCHAR);
            }

            psMedico.executeUpdate();

            JOptionPane.showMessageDialog(null, "Registro guardado correctamente.");
            limpiar();
            cargarTabla();
            cargarDatosCategoriaOtros();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la base de datos: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        String nombretxt = Nombre.getText().trim();
        String apellidotxt = Apellido.getText().trim();
        String citxt = CI.getText().trim();
        String telefonotxt = Telefono.getText().trim();
        Date fechanacimientotxt = FechaNacimiento.getDate();
        String direcciontxt = Direccion.getText().trim();
        String categoriatxt = Categoria.getSelectedItem().toString();
        String especialidadtxt = null;
        String categoriaProfesionalOtro = null;

        if (nombretxt.isEmpty() || apellidotxt.isEmpty() || categoriatxt.isEmpty() || citxt.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, rellene los campos obligatorios: Nombre, Apellido, Categoría y CI.");
            return;
        }

        try {
            Integer.parseInt(citxt);
            if (!telefonotxt.isEmpty()) {
                Integer.parseInt(telefonotxt);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "CI y Teléfono deben ser números válidos.");
            return;
        }

        if (categoriatxt.equals("Especialista")) {
            if (Especialidad.getSelectedItem() == null || Especialidad.getSelectedItem().toString().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, seleccione una especialidad.");
                return;
            }
            especialidadtxt = Especialidad.getSelectedItem().toString().trim();
        } else if (categoriatxt.equals("Otro")) {
            String nombreCat = NombreCategoria.getText().trim();
            Object seleccionadoCombo = ComboCategoriaOtros.getSelectedItem();

            if (!nombreCat.isEmpty()) {
                categoriaProfesionalOtro = nombreCat;
            } else if (seleccionadoCombo != null && !seleccionadoCombo.toString().trim().isEmpty()) {
                categoriaProfesionalOtro = seleccionadoCombo.toString().trim();
            } else {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese o seleccione una categoría profesional válida.");
                return;
            }
        }

        try {
            Connection con = Conexion.obtenerConexion();
            int medicoId = Integer.parseInt(ID.getText());

            PreparedStatement verificarCI = con.prepareStatement("SELECT COUNT(*) FROM medicos WHERE CI = ? AND id_medico != ?");
            verificarCI.setString(1, citxt);
            verificarCI.setInt(2, medicoId);
            ResultSet rs = verificarCI.executeQuery();
            if (rs.next() && rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(null, "Otro médico ya tiene registrado ese mismo CI.");
                rs.close();
                verificarCI.close();
                return;
            }
            rs.close();
            verificarCI.close();

            PreparedStatement psMedico = con.prepareStatement(
                    "UPDATE medicos SET nombre=?, apellido=?, fecha_nacimiento=?, telefono=?, direccion=?, categoria_profesional=?, categoria_profesional_otro=?, especialidad=?, CI=? WHERE id_medico=?"
            );

            psMedico.setString(1, nombretxt);
            psMedico.setString(2, apellidotxt);

            if (fechanacimientotxt != null) {
                psMedico.setDate(3, new java.sql.Date(fechanacimientotxt.getTime()));
            } else {
                psMedico.setNull(3, java.sql.Types.DATE);
            }

            if (!telefonotxt.isEmpty()) {
                psMedico.setString(4, telefonotxt);
            } else {
                psMedico.setNull(4, java.sql.Types.VARCHAR);
            }

            if (!direcciontxt.isEmpty()) {
                psMedico.setString(5, direcciontxt);
            } else {
                psMedico.setNull(5, java.sql.Types.VARCHAR);
            }

            psMedico.setString(6, categoriatxt);

            if (categoriatxt.equals("Otro")) {
                psMedico.setString(7, categoriaProfesionalOtro);
            } else {
                psMedico.setNull(7, java.sql.Types.VARCHAR);
            }

            if (especialidadtxt != null) {
                psMedico.setString(8, especialidadtxt);
            } else {
                psMedico.setNull(8, java.sql.Types.VARCHAR);
            }

            psMedico.setString(9, citxt);
            psMedico.setInt(10, medicoId);

            int filasAfectadas = psMedico.executeUpdate();

            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(null, "Registro modificado correctamente.");
                limpiar();
                cargarTabla();
                cargarDatosCategoriaOtros();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el médico con el ID especificado.");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la base de datos: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        int fila = TablaMedicos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un médico para eliminar");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
                null,
                "¿Está seguro de que desea eliminar este registro?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        int medicoId = Integer.parseInt(ID.getText());

        try {
            Connection con = Conexion.obtenerConexion();

            PreparedStatement psVerificar = con.prepareStatement(
                    "SELECT estado FROM medicos WHERE id_medico = ?"
            );
            psVerificar.setInt(1, medicoId);
            ResultSet rs = psVerificar.executeQuery();

            if (rs.next()) {
                int estado = rs.getInt("estado");

                if (estado == 0) {
                    JOptionPane.showMessageDialog(null, "El médico ya fue eliminado anteriormente");
                    return;
                }

                PreparedStatement psActualizarEstado = con.prepareStatement(
                        "UPDATE medicos SET estado = 0 WHERE id_medico = ?"
                );
                psActualizarEstado.setInt(1, medicoId);
                psActualizarEstado.executeUpdate();

                JOptionPane.showMessageDialog(null, "Registro marcado como eliminado");
                limpiar();
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró al médico seleccionado");
            }
        } catch (SQLException ex) {
            System.out.println("Error en eliminación lógica: " + ex.toString());
            JOptionPane.showMessageDialog(null, "Error en la eliminación lógica: " + ex.getMessage());
        }
    }//GEN-LAST:event_eliminarActionPerformed
    private void limpiar() {
        CI.setText("");
        Nombre.setText("");
        Apellido.setText("");
        FechaNacimiento.setDate(null);
        Telefono.setText("");
        Direccion.setText("");
        Categoria.setSelectedIndex(0); 
        Especialidad.setSelectedIndex(0); 
    }

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_limpiarActionPerformed

    private void TablaMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMedicosMouseClicked
        try {
            int fila = TablaMedicos.getSelectedRow();
            if (fila == -1) {
                return;
            }

            int id = Integer.parseInt(TablaMedicos.getValueAt(fila, 0).toString());

            Connection con = Conexion.obtenerConexion();
            PreparedStatement ps = con.prepareStatement(
                    "SELECT CI, nombre, apellido, fecha_nacimiento, telefono, direccion, categoria_profesional, categoria_profesional_otro, especialidad FROM medicos WHERE id_medico = ?"
            );
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                ID.setText(String.valueOf(id));
                CI.setText(rs.getString("CI"));
                Nombre.setText(rs.getString("nombre"));
                Apellido.setText(rs.getString("apellido"));

                java.sql.Date fecha = rs.getDate("fecha_nacimiento");
                if (fecha != null) {
                    FechaNacimiento.setDate(new java.util.Date(fecha.getTime()));
                } else {
                    FechaNacimiento.setDate(null);
                }

                Telefono.setText(rs.getString("telefono"));
                Direccion.setText(rs.getString("direccion"));

                String categoria = rs.getString("categoria_profesional");
                String especialidad = rs.getString("especialidad");
                String otroCategoria = rs.getString("categoria_profesional_otro");

                if (categoria.equalsIgnoreCase("General")) {
                    Categoria.setSelectedItem("General");
                    Especialidad.setVisible(false);
                    EspecialidadLabel.setVisible(false);
                    NombreCategoria.setVisible(false);
                    OtroLabel.setVisible(false);
                } else if (categoria.equalsIgnoreCase("Especialista")) {
                    Categoria.setSelectedItem("Especialista");
                    Especialidad.setVisible(true);
                    EspecialidadLabel.setVisible(true);
                    NombreCategoria.setVisible(false);
                    OtroLabel.setVisible(false);

                    if (especialidad != null) {
                        Especialidad.setSelectedItem(especialidad);
                    }
                } else {
                    Categoria.setSelectedItem("Otro");
                    NombreCategoria.setVisible(true);
                    OtroLabel.setVisible(true);
                    NombreCategoria.setText(otroCategoria != null ? otroCategoria : "");
                    Especialidad.setVisible(false);
                    EspecialidadLabel.setVisible(false);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_TablaMedicosMouseClicked

    private void btnAdminCajerosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminCajerosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminCajerosMouseExited

    private void btnAdminCajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCajerosActionPerformed
        AdministradorCajeros admincaj = new AdministradorCajeros();
        admincaj.setLocationRelativeTo(null);
        admincaj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminCajerosActionPerformed

    private void btnAdminDocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminDocMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminDocMouseExited

    private void btnAdminDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminDocActionPerformed

    }//GEN-LAST:event_btnAdminDocActionPerformed

    private void btnReportePagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportePagosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportePagosMouseExited

    private void btnReportePagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportePagosActionPerformed
        ReportespagarMedico reportpag = new ReportespagarMedico();
        reportpag.setLocationRelativeTo(null);
        reportpag.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReportePagosActionPerformed

    private void btnServiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServiciosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServiciosMouseExited

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        ServiciosPrecios serv = new ServiciosPrecios();
        serv.setLocationRelativeTo(null);
        serv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnReporteEspeciMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteEspeciMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteEspeciMouseExited

    private void btnReporteEspeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteEspeciActionPerformed
        ReportesGeneral reportprof = new ReportesGeneral();
        reportprof.setLocationRelativeTo(null);
        reportprof.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReporteEspeciActionPerformed

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited

    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Login cerrar = new Login();
        cerrar.setLocationRelativeTo(null);
        cerrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e){
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorDoctores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarTecnico;
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField CI;
    private javax.swing.JComboBox<String> Categoria;
    private javax.swing.JComboBox<String> ComboCategoriaOtros;
    private javax.swing.JTextField Direccion;
    private javax.swing.JComboBox<String> Especialidad;
    private javax.swing.JLabel EspecialidadLabel;
    private com.toedter.calendar.JDateChooser FechaNacimiento;
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel FondoGris;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel ListaPersonal;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField NombreCategoria;
    private javax.swing.JLabel OtroLabel;
    private javax.swing.JPanel Superior;
    private javax.swing.JTable TablaMedicos;
    private javax.swing.JTextField Telefono;
    private javax.swing.JButton btnAdminCajeros;
    private javax.swing.JButton btnAdminDoc;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnReporteEspeci;
    private javax.swing.JButton btnReportePagos;
    private javax.swing.JButton btnServicios;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton modificar;
    // End of variables declaration//GEN-END:variables
}
