/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administrador;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.Date;
import ConexionLogin.Conexion;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author Rafael
 */
public class AdministradorDoctores extends javax.swing.JFrame {

    /**
     * Creates new form AdministradorDoctores
     */
    public AdministradorDoctores() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        cargarTabla();
        ID.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Superior = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ListaPersonal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMedicos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        CI = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        AgregarTecnico = new javax.swing.JLabel();
        EspecialidadLabel = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        HabilitarDeshabilitar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Categoria = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        Especialidad = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        FechaNacimiento = new com.toedter.calendar.JDateChooser();
        Direccion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        NombreCategoria = new javax.swing.JTextField();
        FondoGris = new javax.swing.JLabel();
        FondoBlanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Superior.setBackground(new java.awt.Color(80, 35, 100));
        Superior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaPersonal.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        ListaPersonal.setText("Lista de Médicos");
        jPanel2.add(ListaPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 340, -1));

        TablaMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "CI", "Teléfono", "Fecha de Nacimiento", "Dirección", "Categoria Profesional", "Especialidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMedicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaMedicos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1190, 860));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));

        jTextField1.setBackground(new java.awt.Color(233, 236, 239));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setText("Buscar");
        jTextField1.setToolTipText("");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 15, 90, 20));
        String placeholder = "Buscar CI";

        jTextField1.setText(placeholder);
        jTextField1.setForeground(Color.GRAY);

        jTextField1.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (jTextField1.getText().equals(placeholder)) {
                    jTextField1.setText("");
                    jTextField1.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (jTextField1.getText().isEmpty()) {
                    jTextField1.setText(placeholder);
                    jTextField1.setForeground(Color.GRAY);
                }
            }
        });

        jTextField1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable();
            }

            private void filterTable() {
                String query = jTextField1.getText().toLowerCase();

                if (query.equals(placeholder.toLowerCase())) {
                    TablaMedicos.setRowSorter(null);
                    return;
                }

                TableRowSorter<TableModel> sorter = new TableRowSorter<>(TablaMedicos.getModel());
                TablaMedicos.setRowSorter(sorter);

                if (query.trim().isEmpty()) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + query, 1, 3));
                }
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_1.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 190, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1190, 910));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 194, 194)));
        jPanel1.setToolTipText("");
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Apellido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("CI:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 440, -1));

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 440, -1));

        Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 440, -1));

        CI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIActionPerformed(evt);
            }
        });
        jPanel1.add(CI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 440, -1));

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 10, -1));

        AgregarTecnico.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        AgregarTecnico.setText("Agregar Médicos");
        jPanel1.add(AgregarTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        EspecialidadLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EspecialidadLabel.setText("Especialidad:");
        jPanel1.add(EspecialidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, 20));

        guardar.setBackground(new java.awt.Color(29, 41, 57));
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, -1));

        modificar.setBackground(new java.awt.Color(29, 41, 57));
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 100, -1));

        eliminar.setBackground(new java.awt.Color(255, 0, 0));
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 100, -1));

        limpiar.setBackground(new java.awt.Color(29, 41, 57));
        limpiar.setForeground(new java.awt.Color(255, 255, 255));
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 100, -1));

        HabilitarDeshabilitar.setBackground(new java.awt.Color(29, 41, 57));
        HabilitarDeshabilitar.setForeground(new java.awt.Color(255, 255, 255));
        HabilitarDeshabilitar.setText("Habilitar/Deshabilitar");
        HabilitarDeshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabilitarDeshabilitarActionPerformed(evt);
            }
        });
        jPanel1.add(HabilitarDeshabilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Dirección:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));

        Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Especialista", "Otro"}));
        Especialidad.setVisible(false);
        EspecialidadLabel.setVisible(false);
        Categoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                    String seleccionado = (String) Categoria.getSelectedItem();
                    if ("General".equals(seleccionado)) {
                        Especialidad.setVisible(false);
                        EspecialidadLabel.setVisible(false);
                    } else {
                        Especialidad.setVisible(true);
                        EspecialidadLabel.setVisible(true);
                    }
                }
            }
        });
        jPanel1.add(Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 170, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Nombre de Categoria:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 20));

        Especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "Cardiología",
            "Gastroenterología",
            "Neumología",
            "Neurología",
            "Oncología",
            "Pediatría",
            "Dermatología",
            "Endocrinología",
            "Hematología",
            "Infectología",
            "Reumatología",
            "Neurocirugía",
            "Cirugía Cardiovascular",
            "Cirugía Plástica",
            "Obstetricia",
            "Ginecología",
            "Urología",
            "Oftalmología",
            "Otorrinolaringología",
            "Radiología" }));
jPanel1.add(Especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 170, -1));

jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
jLabel16.setText("Teléfono:");
jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));
jPanel1.add(FechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 440, -1));
jPanel1.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 440, -1));

jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
jLabel17.setText("Fecha de Nacimiento:");
jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
jLabel18.setText("Categoría Profesional:");
jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));
jPanel1.add(NombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 440, -1));

jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 50, 660, 330));

getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1880, 980));

FondoGris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Background.jpg"))); // NOI18N
getContentPane().add(FondoGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_2.png"))); // NOI18N
getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 680, 410));

pack();
}// </editor-fold>//GEN-END:initComponents
    private void cargarTabla() {
            DefaultTableModel modeloTabla = (DefaultTableModel) TablaMedicos.getModel();
            modeloTabla.setRowCount(0);

            try {
                Connection con = Conexion.obtenerConexion();
                PreparedStatement ps = con.prepareStatement(
                        "SELECT id_medico, CI, nombre, apellido, fecha_nacimiento, telefono, direccion, categoria_profesional, especialidad FROM medicos WHERE estado = 1"
                );
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    modeloTabla.addRow(new Object[]{
                        rs.getInt("id_medico"),
                        rs.getString("nombre"),
                        rs.getString("apellido"),
                        rs.getString("CI"),
                        rs.getString("telefono"),
                        rs.getDate("fecha_nacimiento"),
                        rs.getString("direccion"),
                        rs.getString("categoria_profesional"),
                        rs.getString("especialidad")
                    });
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al cargar datos: " + ex.toString());
            }
        }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoActionPerformed

    private void CIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CIActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        ID.setVisible(false);
    }//GEN-LAST:event_IDActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        String nombretxt = Nombre.getText().trim();
        String apellidotxt = Apellido.getText().trim();
        String citxt = CI.getText().trim();
        String telefonotxt = Telefono.getText().trim();
        Date fechanacimientotxt = FechaNacimiento.getDate();
        String direcciontxt = Direccion.getText().trim();
        String categoriatxt = Categoria.getSelectedItem().toString();  // "General", "Especialista", "Otro"
        String especialidadtxt = null;
        String categoriaProfesionalOtro = null;

        if (nombretxt.isEmpty() || apellidotxt.isEmpty() || citxt.isEmpty() || telefonotxt.isEmpty()
                || fechanacimientotxt == null || direcciontxt.isEmpty() || categoriatxt.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, rellene todos los campos obligatorios.");
            return;
        }

        if (categoriatxt.equals("Especialista")) {
            if (Especialidad.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(null, "Por favor, seleccione una especialidad.");
                return;
            }
            especialidadtxt = Especialidad.getSelectedItem().toString().trim();
            if (especialidadtxt.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, seleccione una especialidad.");
                return;
            }
        } else {
            especialidadtxt = null;
        }

        if (categoriatxt.equals("Otro")) {
            categoriaProfesionalOtro = NombreCategoria.getText().trim();  
            if (categoriaProfesionalOtro.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese la categoría profesional.");
                return;
            }
        }

        try {
            Integer.parseInt(citxt);
            Integer.parseInt(telefonotxt);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "CI y Teléfono deben ser números válidos.");
            return;
        }

        String rol = "";
        if (categoriatxt.equals("General")) {
            rol = "Medico General";
        } else if (categoriatxt.equals("Especialista")) {
            rol = "Medico Especialista";
        } else if (categoriatxt.equals("Otro")) {
            rol = "Medico Otro";
        } else {
            JOptionPane.showMessageDialog(null, "Categoría inválida.");
            return;
        }

        String username = JOptionPane.showInputDialog("Ingrese el nombre de usuario");
        if (username == null || username.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El nombre de usuario no puede estar vacío.");
            return;
        }

        String contrasena = JOptionPane.showInputDialog("Ingrese la contraseña");
        if (contrasena == null || contrasena.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "La contraseña no puede estar vacía.");
            return;
        }

        try {
            Connection con = Conexion.obtenerConexion();
            String contrasenaEncriptada = BCrypt.hashpw(contrasena, BCrypt.gensalt());

            PreparedStatement psUsuario = con.prepareStatement(
                    "INSERT INTO usuarios(username, contrasena, rol, activo) VALUES (?, ?, ?, ?)",
                    Statement.RETURN_GENERATED_KEYS);
            psUsuario.setString(1, username);
            psUsuario.setString(2, contrasenaEncriptada);
            psUsuario.setString(3, rol);
            psUsuario.setBoolean(4, true);
            psUsuario.executeUpdate();

            ResultSet rs = psUsuario.getGeneratedKeys();
            int idUsuario = 0;
            if (rs.next()) {
                idUsuario = rs.getInt(1);
            } else {
                JOptionPane.showMessageDialog(null, "Error al obtener el ID del usuario.");
                return;
            }


            PreparedStatement psMedico = con.prepareStatement(
                    "INSERT INTO medicos(id_usuario, CI, nombre, apellido, fecha_nacimiento, telefono, direccion, categoria_profesional, categoria_profesional_otro, especialidad, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)");
            psMedico.setInt(1, idUsuario);
            psMedico.setString(2, citxt);
            psMedico.setString(3, nombretxt);
            psMedico.setString(4, apellidotxt);
            psMedico.setDate(5, new java.sql.Date(fechanacimientotxt.getTime()));
            psMedico.setString(6, telefonotxt);
            psMedico.setString(7, direcciontxt);
            psMedico.setString(8, categoriatxt);

            if (categoriatxt.equals("Otro")) {
                psMedico.setString(9, categoriaProfesionalOtro);
            } else {
                psMedico.setNull(9, java.sql.Types.VARCHAR);
            }

            if (categoriatxt.equals("Especialista")) {
                psMedico.setString(10, especialidadtxt);
            } else {
                psMedico.setNull(10, java.sql.Types.VARCHAR);
            }

            psMedico.executeUpdate();

            JOptionPane.showMessageDialog(null, "Registro guardado correctamente.");

            limpiar();
            cargarTabla();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la base de datos: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        int fila = TablaMedicos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un médico para modificar.");
            return;
        }

        int medicoId = Integer.parseInt(TablaMedicos.getValueAt(fila, 0).toString());

        String nombretxt = Nombre.getText().trim();
        String apellidotxt = Apellido.getText().trim();
        String citxt = CI.getText().trim();
        String telefonotxt = Telefono.getText().trim();
        Date fechanacimientotxt = FechaNacimiento.getDate();
        String direcciontxt = Direccion.getText().trim();
        String categoriatxt = Categoria.getSelectedItem().toString();  // "General" o "Especialista"
        String especialidadtxt = null;

        if (nombretxt.isEmpty() || apellidotxt.isEmpty() || citxt.isEmpty() || telefonotxt.isEmpty()
                || fechanacimientotxt == null || direcciontxt.isEmpty() || categoriatxt.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, rellene todos los campos obligatorios.");
            return;
        }

        if (categoriatxt.equals("Especialista")) {
            if (Especialidad.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(null, "Por favor, seleccione una especialidad.");
                return;
            }
            especialidadtxt = Especialidad.getSelectedItem().toString().trim();
            if (especialidadtxt.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, seleccione una especialidad.");
                return;
            }
        } else {
            especialidadtxt = null;
        }

        try {
            Connection con = Conexion.obtenerConexion();

            String sqlUpdate = "UPDATE medicos SET CI=?, nombre=?, apellido=?, fecha_nacimiento=?, telefono=?, direccion=?, categoria_profesional=?, especialidad=? WHERE id_medico=?";
            PreparedStatement ps = con.prepareStatement(sqlUpdate);
            ps.setString(1, citxt);
            ps.setString(2, nombretxt);
            ps.setString(3, apellidotxt);
            ps.setDate(4, new java.sql.Date(fechanacimientotxt.getTime()));
            ps.setString(5, telefonotxt);
            ps.setString(6, direcciontxt);

            if (categoriatxt.equals("General")) {
                ps.setString(7, "General");
                ps.setNull(8, java.sql.Types.VARCHAR);
            } else {
                ps.setString(7, "Especialista");
                ps.setString(8, especialidadtxt);
            }

            ps.setInt(9, medicoId);

            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Registro modificado correctamente.");
                limpiar();
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(null, "Error al modificar el registro.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la base de datos: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        int fila = TablaMedicos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un médico para eliminar");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
                null,
                "¿Está seguro de que desea eliminar este registro?\nEsta acción deshabilitará al usuario del sistema.",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        int medicoId = Integer.parseInt(ID.getText());

        try {
            Connection con = Conexion.obtenerConexion();

            PreparedStatement psVerificar = con.prepareStatement(
                    "SELECT estado, id_usuario FROM medicos WHERE id_medico = ?"
            );
            psVerificar.setInt(1, medicoId);
            ResultSet rs = psVerificar.executeQuery();

            if (rs.next()) {
                int estado = rs.getInt("estado");
                int idUsuario = rs.getInt("id_usuario");

                if (estado == 0) {
                    JOptionPane.showMessageDialog(null, "El médico ya fue eliminado anteriormente");
                    return;
                }

                PreparedStatement psActualizarEstado = con.prepareStatement(
                        "UPDATE medicos SET estado = 0 WHERE id_medico = ?"
                );
                psActualizarEstado.setInt(1, medicoId);
                psActualizarEstado.executeUpdate();

                PreparedStatement psActualizarUsuario = con.prepareStatement(
                        "UPDATE usuarios SET activo = 0 WHERE id_usuario = ?"
                );
                psActualizarUsuario.setInt(1, idUsuario);
                psActualizarUsuario.executeUpdate();

                JOptionPane.showMessageDialog(null, "Registro marcado como eliminado e inhabilitado para el sistema");
                limpiar();
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró al médico seleccionado");
            }
        } catch (SQLException ex) {
            System.out.println("Error en eliminación lógica: " + ex.toString());
            JOptionPane.showMessageDialog(null, "Error en la eliminación lógica: " + ex.getMessage());
        }
    }//GEN-LAST:event_eliminarActionPerformed
    private void limpiar() {
        CI.setText("");
        Nombre.setText("");
        Apellido.setText("");
        FechaNacimiento.setDate(null);
        Telefono.setText("");
        Direccion.setText("");
        Categoria.setSelectedIndex(0); 
        Especialidad.setSelectedIndex(0); 
    }

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_limpiarActionPerformed

    private void HabilitarDeshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabilitarDeshabilitarActionPerformed
        int fila = TablaMedicos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un médico.");
            return;
        }

        int medicoId = Integer.parseInt(TablaMedicos.getValueAt(fila, 0).toString());

        try {
            Connection con = Conexion.obtenerConexion();

            PreparedStatement psObtenerUsuario = con.prepareStatement("SELECT id_usuario FROM medicos WHERE id_medico=?");
            psObtenerUsuario.setInt(1, medicoId);
            ResultSet rsUsuario = psObtenerUsuario.executeQuery();

            if (!rsUsuario.next()) {
                JOptionPane.showMessageDialog(null, "Error al encontrar el usuario asociado al médico.");
                return;
            }

            int idUsuario = rsUsuario.getInt("id_usuario");


            PreparedStatement psEstado = con.prepareStatement("SELECT activo FROM usuarios WHERE id_usuario=?");
            psEstado.setInt(1, idUsuario);
            ResultSet rsEstado = psEstado.executeQuery();

            if (!rsEstado.next()) {
                JOptionPane.showMessageDialog(null, "Error al encontrar el estado del usuario.");
                return;
            }

            int estadoActual = rsEstado.getInt("activo");

            int nuevoEstado = (estadoActual == 1) ? 0 : 1;

            PreparedStatement psActualizar = con.prepareStatement("UPDATE usuarios SET activo=? WHERE id_usuario=?");
            psActualizar.setInt(1, nuevoEstado);
            psActualizar.setInt(2, idUsuario);
            psActualizar.executeUpdate();

            String mensaje = (nuevoEstado == 1) ? "Médico habilitado." : "Médico deshabilitado.";
            JOptionPane.showMessageDialog(null, mensaje);

            cargarTabla();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_HabilitarDeshabilitarActionPerformed

    private void TablaMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMedicosMouseClicked
        try {
            int fila = TablaMedicos.getSelectedRow();
            if (fila == -1) {

                return;
            }
            int id = Integer.parseInt(TablaMedicos.getValueAt(fila, 0).toString());

            Connection con = Conexion.obtenerConexion();
            PreparedStatement ps = con.prepareStatement(
                "SELECT CI, nombre, apellido, fecha_nacimiento, telefono, direccion, categoria_profesional, especialidad "
                + "FROM medicos WHERE id_medico = ?"
            );
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                ID.setText(String.valueOf(id));
                CI.setText(rs.getString("CI"));
                Nombre.setText(rs.getString("nombre"));
                Apellido.setText(rs.getString("apellido"));

                java.sql.Date fecha = rs.getDate("fecha_nacimiento");
                if (fecha != null) {
                    FechaNacimiento.setDate(new java.util.Date(fecha.getTime()));
                } else {
                    FechaNacimiento.setDate(null);
                }

                Telefono.setText(rs.getString("telefono"));
                Direccion.setText(rs.getString("direccion"));

                String categoria = rs.getString("categoria_profesional");
                String especialidad = rs.getString("especialidad");

                if (categoria != null) {
                    categoria = categoria.trim();
                } else {
                    categoria = "";
                }
                if (especialidad != null) {
                    especialidad = especialidad.trim();
                } else {
                    especialidad = "";
                }

                if (categoria.equalsIgnoreCase("General") || categoria.equalsIgnoreCase("General")) {
                    Categoria.setSelectedItem("General");
                    Especialidad.setVisible(false);
                    EspecialidadLabel.setVisible(false);
                    Especialidad.setSelectedIndex(-1);
                } else if (categoria.equalsIgnoreCase("Especialista") || categoria.equalsIgnoreCase("Especialista")) {
                    Categoria.setSelectedItem("Especialista");
                    Especialidad.setVisible(true);
                    EspecialidadLabel.setVisible(true);

                    boolean encontrada = false;
                    for (int i = 0; i < Especialidad.getItemCount(); i++) {
                        String item = Especialidad.getItemAt(i).trim();
                        if (item.equalsIgnoreCase(especialidad)) {
                            Especialidad.setSelectedIndex(i);
                            encontrada = true;
                            break;
                        }
                    }

                    if (!encontrada && !especialidad.isEmpty()) {
                        Especialidad.addItem(especialidad);
                        Especialidad.setSelectedItem(especialidad);
                    }
                } else {
                    Categoria.setSelectedIndex(-1);
                    Especialidad.setVisible(false);
                    EspecialidadLabel.setVisible(false);
                    Especialidad.setSelectedIndex(-1);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_TablaMedicosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e){
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorDoctores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarTecnico;
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField CI;
    private javax.swing.JComboBox<String> Categoria;
    private javax.swing.JTextField Direccion;
    private javax.swing.JComboBox<String> Especialidad;
    private javax.swing.JLabel EspecialidadLabel;
    private com.toedter.calendar.JDateChooser FechaNacimiento;
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel FondoGris;
    private javax.swing.JButton HabilitarDeshabilitar;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel ListaPersonal;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField NombreCategoria;
    private javax.swing.JPanel Superior;
    private javax.swing.JTable TablaMedicos;
    private javax.swing.JTextField Telefono;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton modificar;
    // End of variables declaration//GEN-END:variables
}
