/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cajero;

import ConexionLogin.Conexion;
import ConexionLogin.Login;
import Servicios.GenerarFicha;
import Servicios.PreciosServiciosCajero;

import com.formdev.flatlaf.FlatLightLaf;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Rafael
 */
public class RegistrarPacientes extends javax.swing.JFrame {
    private int idusuario; 

    /**
     * Creates new form RegistrarPacientes
     */
    public RegistrarPacientes(int idusuario) {
        this.idusuario = idusuario;
        initComponents();
        generarNumeroHistorial();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        cargarTabla();
        ID.setVisible(false);
        ID.setEnabled(false);
        ID.setFocusable(false);
        ID.setRequestFocusEnabled(false);
    }
    
    private TableRowSorter<DefaultTableModel> sorter;
    
    private RegistrarPacientes() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Superior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnPacientes = new javax.swing.JButton();
        btnFichas = new javax.swing.JButton();
        btnServicio = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ListaPersonal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        txtNumeroHistorial = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        AgregarTecnico = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        FechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        CI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        FondoGris = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Superior.setBackground(new java.awt.Color(0, 102, 255));
        Superior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrarsesion.png"))); // NOI18N
        Superior.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, 20, 20));

        btnCerrarSesion.setBackground(new java.awt.Color(7, 70, 215));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setHorizontalAlignment(SwingConstants.LEFT);
        btnCerrarSesion.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnCerrarSesion.setIconTextGap(10);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        Superior.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 170, 40));

        btnPacientes.setBackground(new java.awt.Color(7, 70, 215));
        btnPacientes.setForeground(new java.awt.Color(241, 241, 241));
        btnPacientes.setText("Pacientes");
        btnPacientes.setBorder(null);
        btnPacientes.setHorizontalAlignment(SwingConstants.LEFT);
        btnPacientes.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnPacientes.setIconTextGap(10);
        btnPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPacientesMouseExited(evt);
            }
        });
        btnPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientesActionPerformed(evt);
            }
        });
        Superior.add(btnPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 190, 40));

        btnFichas.setBackground(new java.awt.Color(7, 70, 215));
        btnFichas.setForeground(new java.awt.Color(241, 241, 241));
        btnFichas.setText("Fichas");
        btnFichas.setBorder(null);
        btnFichas.setHorizontalAlignment(SwingConstants.LEFT);
        btnFichas.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnFichas.setIconTextGap(10);
        btnFichas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFichasMouseExited(evt);
            }
        });
        btnFichas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichasActionPerformed(evt);
            }
        });
        Superior.add(btnFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        btnServicio.setBackground(new java.awt.Color(7, 70, 215));
        btnServicio.setForeground(new java.awt.Color(241, 241, 241));
        btnServicio.setText("Precios de Servicios");
        btnServicio.setBorder(null);
        btnPacientes.setHorizontalAlignment(SwingConstants.LEFT);
        btnPacientes.setBorder(BorderFactory.createEmptyBorder(0, 35, 0, 0));
        btnPacientes.setIconTextGap(10);
        btnServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnServicioMouseExited(evt);
            }
        });
        btnServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicioActionPerformed(evt);
            }
        });
        Superior.add(btnServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 190, 40));

        getContentPane().add(Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaPersonal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ListaPersonal.setText("Pacientes");
        jPanel2.add(ListaPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        tblPacientes.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "CI", "Teléfono", "Fecha de Nacimiento", "Número de historial clinico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPacientesMouseClicked(evt);
            }
        });
        tblPacientes.getTableHeader().setReorderingAllowed(false);
        tblPacientes.getTableHeader().setResizingAllowed(false);
        tblPacientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblPacientes.setFocusable(false);
        jScrollPane1.setViewportView(tblPacientes);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 870, 610));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(233, 236, 239));
        jTextField1.setText("Buscar Paciente");
        jTextField1.setToolTipText("");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, 20));
        String placeholder = "Buscar Fichas";
        jTextField1.setText(placeholder);
        jTextField1.setForeground(Color.GRAY);

        jTextField1.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (jTextField1.getText().equals(placeholder)) {
                    jTextField1.setText("");
                    jTextField1.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (jTextField1.getText().trim().isEmpty()) {
                    jTextField1.setText(placeholder);
                    jTextField1.setForeground(Color.GRAY);
                }
            }
        });

        jTextField1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable();
            }

            private void filterTable() {
                String query = normalize(jTextField1.getText().trim());

                if (query.equals(normalize(placeholder)) || query.isEmpty()) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(new RowFilter<TableModel, Integer>() {
                        @Override
                        public boolean include(Entry<? extends TableModel, ? extends Integer> entry) {
                            String historial = normalize(String.valueOf(entry.getValue(6)));
                            String nombre = normalize(entry.getStringValue(1).trim());
                            String apellido = normalize(entry.getStringValue(2).trim());
                            String ci = normalize(String.valueOf(entry.getValue(3)));
                            String combinado = nombre + " " + apellido;

                            return historial.contains(query) || nombre.contains(query) || apellido.contains(query) || combinado.contains(query) || ci.contains(query);

                        }
                    });
                }
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_1.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 190, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 880, 660));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 194, 194)));
        jPanel1.setToolTipText("");
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        jLabel5.setText("Número de historial clinico");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        jLabel6.setText("CI:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 280, -1));

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 280, -1));

        Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 280, -1));

        txtNumeroHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroHistorialActionPerformed(evt);
            }
        });
        txtNumeroHistorial.setEditable(false);
        txtNumeroHistorial.setFocusable(false);
        jPanel1.add(txtNumeroHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 280, -1));

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 10, 10));

        AgregarTecnico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AgregarTecnico.setText("Registrar Pacientes");
        jPanel1.add(AgregarTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        guardar.setBackground(new java.awt.Color(7, 70, 215));
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 100, 30));

        modificar.setBackground(new java.awt.Color(7, 70, 215));
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 100, 30));

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 100, 30));

        jLabel16.setText("Teléfono:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));
        jPanel1.add(FechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 280, -1));

        jLabel17.setText("Fecha de Nacimiento:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        CI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIActionPerformed(evt);
            }
        });
        jPanel1.add(CI, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 280, -1));

        jLabel7.setText("Apellido:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(889, 40, 450, 280));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1350, 710));

        FondoGris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Background.jpg"))); // NOI18N
        getContentPane().add(FondoGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(-510, -40, 1910, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void cargarTabla() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                switch (columnIndex) {
                    case 0: 
                    case 6: 
                        return Integer.class;
                    case 5: 
                        return Date.class;
                    default:
                        return String.class;
                }
            }
        };
        modelo.setColumnIdentifiers(new Object[]{
            "ID", "Nombre", "Apellido", "CI", "Teléfono", "Fecha de Nacimiento", "Número de historial clínico"
        });

        try {
            Connection con = Conexion.obtenerConexion();
            PreparedStatement ps = con.prepareStatement(
                    "SELECT id_paciente, nombre, apellido, CI, telefono, fecha_nacimiento, numero_historial FROM pacientes"
            );
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("id_paciente"), 
                    rs.getString("nombre"),
                    rs.getString("apellido"),
                    rs.getString("CI"),
                    rs.getString("telefono"),
                    rs.getDate("fecha_nacimiento"),
                    rs.getInt("numero_historial") 
                });
            }

            tblPacientes.setModel(modelo);


            sorter = new TableRowSorter<>(modelo);
            tblPacientes.setRowSorter(sorter);


            List<RowSorter.SortKey> sortKeys = new ArrayList<>();
            sortKeys.add(new RowSorter.SortKey(0, SortOrder.DESCENDING)); 
            sorter.setSortKeys(sortKeys);
            sorter.sort();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar los pacientes: " + ex.getMessage());
            ex.printStackTrace();
        }
    }


    public static String normalizar(String input) {
        if (input == null) {
            return null;
        }
        String normalized = Normalizer.normalize(input, Normalizer.Form.NFD);
        normalized = normalized.replaceAll("\\p{InCombiningDiacriticalMarks}+", "");
        return normalized.toLowerCase();
    }
    
    private void generarNumeroHistorial() {
        try {
            Connection con = Conexion.obtenerConexion();
            PreparedStatement ps = con.prepareStatement(
                    "SELECT IFNULL(MAX(numero_historial), 0) + 1 AS siguiente FROM pacientes"
            );
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                int numeroHistorial = rs.getInt("siguiente");
                txtNumeroHistorial.setText(String.valueOf(numeroHistorial));
            }
            rs.close();
            ps.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al generar número de historial: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited

    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Login cerrar = new Login();
        cerrar.setLocationRelativeTo(null);
        cerrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String query = normalize(jTextField1.getText().trim());
        if (!query.isEmpty()) {
            sorter.setRowFilter(new RowFilter<TableModel, Integer>() {
                @Override
                public boolean include(Entry<? extends TableModel, ? extends Integer> entry) {
                    String historial = normalize(String.valueOf(entry.getValue(6)));
                    String nombre = normalize(entry.getStringValue(1).trim());
                    String apellido = normalize(entry.getStringValue(2).trim());
                    String ci = normalize(String.valueOf(entry.getValue(3)));

                    return historial.equals(query) || nombre.equalsIgnoreCase(query)
                            || apellido.equalsIgnoreCase(query) || ci.equals(query);
                }
            });
        } else {
            sorter.setRowFilter(null);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed
    private String normalize(String text) {
        if (text == null) return "";
        String normalized = Normalizer.normalize(text, Normalizer.Form.NFD);
        normalized = normalized.replaceAll("\\p{InCombiningDiacriticalMarks}+", "");
        return normalized.toLowerCase();
    }
    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoActionPerformed

    private void txtNumeroHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroHistorialActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        ID.setVisible(false);
        ID.setEnabled(false);
        ID.setFocusable(false);
        ID.setRequestFocusEnabled(false);
    }//GEN-LAST:event_IDActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        String nombretxt = Nombre.getText().trim();
        String apellidotxt = Apellido.getText().trim();
        String citxt = CI.getText().trim();
        String telefonotxt = Telefono.getText().trim();
        Date fechanacimientotxt = FechaNacimiento.getDate();


        if (nombretxt.isEmpty() || apellidotxt.isEmpty() || citxt.isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Por favor, rellene los campos obligatorios: Nombre, Apellido y CI.");
            return;
        }

        try {
            Long.parseLong(citxt); 
            if (!telefonotxt.isEmpty()) {
                Long.parseLong(telefonotxt); 
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "CI y Teléfono deben ser números válidos.");
            return;
        }

        try {
            Connection con = Conexion.obtenerConexion();

            int numeroHistorial = 1;
            PreparedStatement psMax = con.prepareStatement(
                    "SELECT IFNULL(MAX(numero_historial), 0) + 1 AS siguiente FROM pacientes"
            );
            ResultSet rsMax = psMax.executeQuery();
            if (rsMax.next()) {
                numeroHistorial = rsMax.getInt("siguiente");
            }
            rsMax.close();
            psMax.close();

            PreparedStatement verificarCI = con.prepareStatement(
                    "SELECT COUNT(*) FROM pacientes WHERE CI = ?"
            );
            verificarCI.setString(1, citxt);
            ResultSet rs = verificarCI.executeQuery();
            if (rs.next() && rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(null,
                        "Ya existe un paciente registrado con el mismo CI.");
                rs.close();
                verificarCI.close();
                return;
            }
            rs.close();
            verificarCI.close();

            PreparedStatement ps = con.prepareStatement(
                    "INSERT INTO pacientes "
                    + "(CI, nombre, apellido, fecha_nacimiento, telefono, direccion, numero_historial) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?)"
            );

            ps.setString(1, citxt);
            ps.setString(2, nombretxt);
            ps.setString(3, apellidotxt);

            if (fechanacimientotxt != null) {
                ps.setDate(4, new java.sql.Date(fechanacimientotxt.getTime()));
            } else {
                ps.setNull(4, java.sql.Types.DATE);
            }

            if (!telefonotxt.isEmpty()) {
                ps.setString(5, telefonotxt);
            } else {
                ps.setNull(5, java.sql.Types.VARCHAR);
            }

            ps.setNull(6, java.sql.Types.VARCHAR); 
            ps.setInt(7, numeroHistorial);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null,
                    "Paciente registrado correctamente.\nHistorial clínico: " + numeroHistorial);

            limpiar();
            cargarTabla();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la base de datos: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        int fila = tblPacientes.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un paciente de la tabla para modificar.");
            return;
        }

        int confirmar = JOptionPane.showConfirmDialog(null,
                "¿Está seguro que desea modificar este paciente?",
                "Confirmar modificación",
                JOptionPane.YES_NO_OPTION);

        if (confirmar != JOptionPane.YES_OPTION) {
            return; 
        }

        int idPaciente = Integer.parseInt(tblPacientes.getValueAt(fila, 0).toString());
        String nombretxt = Nombre.getText().trim();
        String apellidotxt = Apellido.getText().trim();
        String citxt = CI.getText().trim();
        String telefonotxt = Telefono.getText().trim();
        Date fechanacimientotxt = FechaNacimiento.getDate();

        if (nombretxt.isEmpty() || apellidotxt.isEmpty() || citxt.isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Por favor, rellene los campos obligatorios: Nombre, Apellido y CI.");
            return;
        }

        try {
            Long.parseLong(citxt);
            if (!telefonotxt.isEmpty()) {
                Long.parseLong(telefonotxt);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "CI y Teléfono deben ser números válidos.");
            return;
        }

        try {
            Connection con = Conexion.obtenerConexion();

            PreparedStatement verificarCI = con.prepareStatement(
                    "SELECT COUNT(*) FROM pacientes WHERE CI = ? AND id_paciente != ?"
            );
            verificarCI.setString(1, citxt);
            verificarCI.setInt(2, idPaciente);
            ResultSet rs = verificarCI.executeQuery();
            if (rs.next() && rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(null,
                        "Ya existe otro paciente registrado con el mismo CI.");
                rs.close();
                verificarCI.close();
                return;
            }
            rs.close();
            verificarCI.close();

            PreparedStatement ps = con.prepareStatement(
                    "UPDATE pacientes SET nombre = ?, apellido = ?, CI = ?, fecha_nacimiento = ?, telefono = ? "
                    + "WHERE id_paciente = ?"
            );

            ps.setString(1, nombretxt);
            ps.setString(2, apellidotxt);
            ps.setString(3, citxt);
            if (fechanacimientotxt != null) {
                ps.setDate(4, new java.sql.Date(fechanacimientotxt.getTime()));
            } else {
                ps.setNull(4, java.sql.Types.DATE);
            }
            if (!telefonotxt.isEmpty()) {
                ps.setString(5, telefonotxt);
            } else {
                ps.setNull(5, java.sql.Types.VARCHAR);
            }

            ps.setInt(6, idPaciente);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Paciente modificado correctamente.");
            limpiar();
            cargarTabla();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la base de datos: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_limpiarActionPerformed
    private void limpiar() {
        ID.setText(""); 
        Nombre.setText("");
        Apellido.setText("");
        CI.setText("");
        Telefono.setText("");
        FechaNacimiento.setDate(null);
        generarNumeroHistorial(); 
    }
    private void tblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPacientesMouseClicked
        try {
            int fila = tblPacientes.getSelectedRow();
            if (fila == -1) {
                return;
            }

            int idPaciente = Integer.parseInt(tblPacientes.getValueAt(fila, 0).toString());

            Connection con = Conexion.obtenerConexion();
            PreparedStatement ps = con.prepareStatement(
                    "SELECT nombre, apellido, CI, telefono, fecha_nacimiento, numero_historial FROM pacientes WHERE id_paciente = ?"
            );
            ps.setInt(1, idPaciente);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                ID.setText(String.valueOf(idPaciente));
                Nombre.setText(rs.getString("nombre"));
                Apellido.setText(rs.getString("apellido"));
                CI.setText(rs.getString("CI"));
                Telefono.setText(rs.getString("telefono"));
                FechaNacimiento.setDate(rs.getDate("fecha_nacimiento"));
                txtNumeroHistorial.setText(String.valueOf(rs.getInt("numero_historial")));
            }

            rs.close();
            ps.close();
            con.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar datos del paciente: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tblPacientesMouseClicked

    private void CIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CIActionPerformed

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void btnPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPacientesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPacientesMouseExited

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed

    }//GEN-LAST:event_btnPacientesActionPerformed

    private void btnFichasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFichasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFichasMouseExited

    private void btnFichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichasActionPerformed
        GenerarFicha SelecDoc = new GenerarFicha(idusuario);
        SelecDoc.setLocationRelativeTo(null);
        SelecDoc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFichasActionPerformed

    private void btnServicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServicioMouseExited

    private void btnServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicioActionPerformed
        PreciosServiciosCajero SelecDoc = new PreciosServiciosCajero();
        SelecDoc.setLocationRelativeTo(null);
        SelecDoc.setVisible(true);
    }//GEN-LAST:event_btnServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarTecnico;
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField CI;
    private com.toedter.calendar.JDateChooser FechaNacimiento;
    private javax.swing.JLabel FondoGris;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel ListaPersonal;
    private javax.swing.JTextField Nombre;
    private javax.swing.JPanel Superior;
    private javax.swing.JTextField Telefono;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnFichas;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JButton btnServicio;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton modificar;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JTextField txtNumeroHistorial;
    // End of variables declaration//GEN-END:variables
}
